Repository stnolting/neorv32, pull requests merged in 2021-12, with the labels that each got.

#229 TRNG and Vivado block designs
  docs/userguide/packaging_vivado.adoc
Labels: DOC

#228 ⚠️ Remove legacy SW (compatibility) wrappers
  CHANGELOG.md
  docs/datasheet/software.adoc
  rtl/core/neorv32_package.vhd
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_legacy.h
  sw/lib/include/neorv32_uart.h
  sw/lib/source/neorv32_uart.c
Labels: SW

#230 :bug: Fix Wishbone timeout bug
  CHANGELOG.md
  rtl/core/neorv32_bus_keeper.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_wishbone.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
Labels: bug, HW

#231 Add SYSINFO flag to check if processor is being simulated
  CHANGELOG.md
  docs/datasheet/soc_sysinfo.adoc
  docs/userguide/simulating_the_processor.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
Labels: enhancement, HW

#225 Add a System View Description (SVD) file
  README.md
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/software.adoc
  sw/README.md
  sw/svd/README.md
  sw/svd/neorv32.svd
Labels: help wanted, SW

#236 ⚠️ Rework FIRQ System (re-rework): use MIP to clear/ack IRQs
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_cfs.adoc
  docs/datasheet/soc_gptmr.adoc
  docs/datasheet/soc_neoled.adoc
  docs/datasheet/soc_slink.adoc
  docs/datasheet/soc_spi.adoc
  docs/datasheet/soc_twi.adoc
  docs/datasheet/soc_uart.adoc
  docs/datasheet/soc_wdt.adoc
  docs/datasheet/soc_xirq.adoc
  rtl/core/neorv32_cfs.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_gptmr.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_uart.vhd
  rtl/core/neorv32_wdt.vhd
  rtl/core/neorv32_xirq.vhd
  sw/example/demo_gptmr/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_gptmr.h
  sw/lib/source/neorv32_gptmr.c
  sw/lib/source/neorv32_xirq.c
  sw/svd/neorv32.svd
Labels: enhancement, riscv-compliance, HW

#235 [sw/example] add SLINK demo program
  sw/example/demo_slink/main.c
  sw/example/demo_slink/makefile
Labels: SW

#237 📚 [SW makefile] add variables to help target
  docs/datasheet/software.adoc
  sw/common/common.mk
Labels: DOC, SW

#238 MULDIV optimization
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_package.vhd
Labels: HW

#221 [setups/osflow] update README
  setups/osflow/README.md
Labels: DOC, help wanted

#240 Faster mul/div operations
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_package.vhd
Labels: HW

#243 Fix compile error with questa, for issue #242
  rtl/core/neorv32_package.vhd
Labels: bug, HW

#241 ⚠️ Make PWM and XIRQ IOs fixed-sized
  docs/datasheet/soc.adoc
  docs/datasheet/soc_pwm.adoc
  docs/datasheet/soc_xirq.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_pwm.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_xirq.vhd
  rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd
  rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  setups/radiant/UPduino_v3/neorv32_upduino_v3_top.vhd
Labels: HW
