Repository stnolting/neorv32, pull requests merged in 2021-06, with the labels that each got.

#53 docs: split User Guide
  .github/workflows/Documentation.yml
  .gitignore
  Makefile
  README.md
  docs/datasheet/content.adoc
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/index.adoc
  docs/datasheet/main.adoc
  docs/datasheet/on_chip_debugger.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_bootrom.adoc
  docs/datasheet/soc_cfs.adoc
  docs/datasheet/soc_dmem.adoc
  docs/datasheet/soc_gpio.adoc
  docs/datasheet/soc_icache.adoc
  docs/datasheet/soc_imem.adoc
  docs/datasheet/soc_mtime.adoc
  docs/datasheet/soc_nco.adoc
  docs/datasheet/soc_neoled.adoc
  docs/datasheet/soc_pwm.adoc
  docs/datasheet/soc_spi.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/soc_trng.adoc
  docs/datasheet/soc_twi.adoc
  docs/datasheet/soc_uart.adoc
  docs/datasheet/soc_wdt.adoc
  docs/datasheet/soc_wishbone.adoc
  docs/datasheet/software.adoc
  docs/icons/important.png
  docs/icons/note.png
  docs/icons/tip.png
  docs/icons/warning.png
  docs/legal.adoc
  docs/neorv32-theme.yml
  docs/userguide/content.adoc
  docs/userguide/index.adoc
  docs/userguide/main.adoc
Labels: documentation

#76 [setups/examples] add iCESugar Minimal
  .github/generate-job-matrix.py
  setups/examples/Makefile
  setups/examples/neorv32_iCESugar_BoardTop_Minimal.vhd
  setups/osflow/devices/ice40/sb_ice40_components.vhd
Labels: enhancement

#89 Make uart_rx a verification component
  sim/neorv32_tb.vhd
  sim/run.py
  sim/uart_rx.vhd
  sim/uart_rx_pkg.vhd
Labels: delayed, enhancement
