Repository stnolting/neorv32, pull requests merged in 2021-09, with the labels that each got.

#154 fix typo wb_mem_a.cyc on sim example
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
Labels: bug

#158 rework low-level hardware access
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_cfs.adoc
  docs/datasheet/soc_gpio.adoc
  docs/datasheet/soc_mtime.adoc
  docs/datasheet/soc_neoled.adoc
  docs/datasheet/soc_pwm.adoc
  docs/datasheet/soc_slink.adoc
  docs/datasheet/soc_spi.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/soc_trng.adoc
  docs/datasheet/soc_twi.adoc
  docs/datasheet/soc_uart.adoc
  docs/datasheet/soc_wdt.adoc
  docs/datasheet/soc_wishbone.adoc
  docs/datasheet/soc_xirq.adoc
  docs/datasheet/software.adoc
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  sw/bootloader/bootloader.c
  sw/example/bitmanip_test/main.c
  sw/example/coremark/core_portme.c
  sw/example/demo_neopixel/main.c
  sw/example/demo_twi/main.c
  sw/example/dhrystone/dhry_1.c
  sw/example/floating_point_test/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_cpu.h
  sw/lib/include/neorv32_legacy.h
  sw/lib/include/neorv32_neoled.h
  sw/lib/include/neorv32_slink.h
  sw/lib/source/neorv32_cfs.c
  sw/lib/source/neorv32_cpu.c
  sw/lib/source/neorv32_gpio.c
  sw/lib/source/neorv32_mtime.c
  sw/lib/source/neorv32_neoled.c
  sw/lib/source/neorv32_pwm.c
  sw/lib/source/neorv32_rte.c
  sw/lib/source/neorv32_slink.c
  sw/lib/source/neorv32_spi.c
  sw/lib/source/neorv32_trng.c
  sw/lib/source/neorv32_twi.c
  sw/lib/source/neorv32_uart.c
  sw/lib/source/neorv32_wdt.c
  sw/lib/source/neorv32_xirq.c
Labels: documentation, enhancement

#152 Adding NEORV32 Qsys/Platform Designer component and AvalonMM Master Interface wrapper
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  setups/README.md
  setups/quartus/de0-nano-test-setup-avalonmm-wrapper/.gitignore
  setups/quartus/de0-nano-test-setup-avalonmm-wrapper/README.md
  setups/quartus/de0-nano-test-setup-avalonmm-wrapper/de0-nano-test-setup.qpf
  setups/quartus/de0-nano-test-setup-avalonmm-wrapper/de0-nano-test-setup.qsf
  setups/quartus/de0-nano-test-setup-avalonmm-wrapper/dmem_ram.qip
  setups/quartus/de0-nano-test-setup-avalonmm-wrapper/dmem_ram.vhd
  setups/quartus/de0-nano-test-setup-avalonmm-wrapper/neorv32_test_setup_avalonmm.vhd
  setups/quartus/de0-nano-test-setup-qsys/.gitignore
  setups/quartus/de0-nano-test-setup-qsys/README.md
  setups/quartus/de0-nano-test-setup-qsys/User_Components.ipx
  setups/quartus/de0-nano-test-setup-qsys/de0-nano-test-setup.qpf
  setups/quartus/de0-nano-test-setup-qsys/de0-nano-test-setup.qsf
  setups/quartus/de0-nano-test-setup-qsys/de0-nano-test-setup.sdc
  setups/quartus/de0-nano-test-setup-qsys/figures/neorv32_platform_designer.png
  setups/quartus/de0-nano-test-setup-qsys/neorv32_ProcessorTop_Test.vhd
  setups/quartus/de0-nano-test-setup-qsys/neorv32_test_qsys.qsys
  setups/quartus/neorv32_qsys_component/README.md
  setups/quartus/neorv32_qsys_component/figures/gui_settings.png
  setups/quartus/neorv32_qsys_component/figures/overview.png
  setups/quartus/neorv32_qsys_component/neorv32_qsys.qip
  setups/quartus/neorv32_qsys_component/neorv32_qsys.vhd
  setups/quartus/neorv32_qsys_component/neorv32_qsys_hw.tcl
Labels: enhancement
