Repository stnolting/neorv32, pull requests merged in 2021-11, with the labels that each got.

#192 RISC-V "Zicntr" and "Zihpm" extensions
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/figures/neorv32_processor.png
  docs/references/riscv-privileged.pdf
  docs/references/riscv-spec.pdf
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd
  rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  rtl/test_setups/neorv32_test_setup_approm.vhd
  rtl/test_setups/neorv32_test_setup_bootloader.vhd
  setups/radiant/UPduino_v3/neorv32_upduino_v3_top.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_cpu.c
  sw/lib/source/neorv32_rte.c
Labels: riscv-compliance

#204 CPU logic optimization
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: HW

#209 [TWI] remove clock-stretching enable flag
  CHANGELOG.md
  docs/datasheet/soc_twi.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_twi.vhd
  sw/example/demo_twi/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_twi.h
  sw/lib/source/neorv32_twi.c
Labels: HW

#212 Rework TRNG module
  CHANGELOG.md
  docs/datasheet/soc_trng.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_trng.vhd
  sw/example/demo_trng/main.c
  sw/lib/source/neorv32_trng.c
Labels: enhancement, HW

#215 Added a example serial terminal program for Linux
  docs/userguide/content.adoc
Labels: DOC

#216 [On-Chip Debugger] Fix JTAG timing
  CHANGELOG.md
  docs/datasheet/on_chip_debugger.adoc
  rtl/core/neorv32_debug_dtm.vhd
  rtl/core/neorv32_package.vhd
Labels: HW

#223 Fix neorv32_gpio_port_get()
  sw/lib/source/neorv32_gpio.c
Labels: bug, SW

#222 [docs/userguide] split user guide into several files
  docs/userguide/adding_custom_hw_modules.adoc
  docs/userguide/application_program_compilation.adoc
  docs/userguide/application_specific_configuration.adoc
  docs/userguide/building_the_documentation.adoc
  docs/userguide/content.adoc
  docs/userguide/customizing_the_bootloader.adoc
  docs/userguide/debugging_with_ocd.adoc
  docs/userguide/enabling_riscv_extensions.adoc
  docs/userguide/executable_upload.adoc
  docs/userguide/free_rtos_support.adoc
  docs/userguide/general_hw_setup.adoc
  docs/userguide/general_sw_framework_setup.adoc
  docs/userguide/installing_an_executable.adoc
  docs/userguide/new_application_project.adoc
  docs/userguide/packaging_vivado.adoc
  docs/userguide/programming_an_external_spi_flash_via_bootloader.adoc
  docs/userguide/riscv_architecture_tests.adoc
  docs/userguide/simulating_the_processor.adoc
  docs/userguide/sw_toolchain_setup.adoc
  docs/userguide/zephyr_support.adoc
Labels: DOC
