Repository stnolting/neorv32, pull requests merged in 2022-06, with the labels that each got.

#329 :bug: fix debugger single-instruction stepping mode
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, HW

#331 :sparkles: Add watchdog pause flag
  CHANGELOG.md
  docs/datasheet/soc_wdt.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_wdt.vhd
  sw/lib/include/neorv32.h
  sw/svd/neorv32.svd
Labels: enhancement, HW

#334 [rtl] add hardware reset to IO/peripheral devices
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/software.adoc
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_cfs.vhd
  rtl/core/neorv32_gpio.vhd
  rtl/core/neorv32_gptmr.vhd
  rtl/core/neorv32_icache.vhd
  rtl/core/neorv32_mtime.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_pwm.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_uart.vhd
  rtl/core/neorv32_wishbone.vhd
  rtl/core/neorv32_xip.vhd
  rtl/core/neorv32_xirq.vhd
  sw/common/crt0.S
  sw/lib/source/neorv32_xip.c
  sw/lib/source/neorv32_xirq.c
Labels: enhancement, HW

#336 :bug: fix SPI & XIP clock phase offset
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_xip.vhd
Labels: bug, HW

#338 [rtl] split executable images into package and body
  CHANGELOG.md
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  sw/image_gen/image_gen.c
Labels: optimization

#340 [rtl] rework TWI module
  CHANGELOG.md
  docs/datasheet/soc_twi.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_twi.vhd
  sw/example/demo_twi/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_twi.h
  sw/lib/source/neorv32_twi.c
  sw/svd/neorv32.svd
Labels: enhancement, HW, optimization

#344 [rtl] add Wishbone output "gating"
  CHANGELOG.md
  docs/datasheet/soc_wishbone.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_wishbone.vhd
Labels: HW

#345 [rtl] rework reset system
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_wdt.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_wdt.vhd
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_wdt.c
  sw/svd/neorv32.svd
Labels: HW, optimization

#349 ⚠️ [rtl] rework SLINK module
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_slink.adoc
  docs/figures/stream_link_interface.png
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/demo_slink/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_slink.h
  sw/lib/source/neorv32_slink.c
Labels: enhancement, HW, optimization

#351 [rtl] minor clean-ups/optimizations
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_package.vhd
Labels: HW

#352 [rtl] add "async TX" Wishbone option
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_wishbone.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_wishbone.vhd
  rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
Labels: enhancement, HW

#353 🧪 [rtl/system_integration] add LiteX core complex wrapper
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
Labels: HW, experimental
