Repository stnolting/neorv32, pull requests merged in 2022-08, with the labels that each got.

#382 [sw example] demo_spi_irq can handle FIFO
  sw/example/demo_spi_irq/drv/neorv32_spi_irq.c
  sw/example/demo_spi_irq/drv/neorv32_spi_irq.h
  sw/example/demo_spi_irq/main.c
Labels: enhancement, SW

#381 ✨ [rtl] add optional SPI data FIFO
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_spi.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/bootloader/bootloader.c
  sw/example/demo_spi/main.c
  sw/example/demo_spi_irq/drv/neorv32_spi_irq.c
  sw/example/demo_spi_irq/drv/neorv32_spi_irq.h
  sw/example/demo_spi_irq/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_spi.h
  sw/lib/source/neorv32_spi.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#383 [rtl] minor cleanups and optimizations
  CHANGELOG.md
  rtl/core/neorv32_cpu_bus.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_uart.vhd
Labels: HW

#384 [rtl] minor cleanup
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_fifo.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_uart.vhd
Labels: HW

#385 change base address of BUSKEEPER
  CHANGELOG.md
  docs/datasheet/soc_buskeeper.adoc
  rtl/core/neorv32_package.vhd
  sw/lib/include/neorv32.h
  sw/svd/neorv32.svd
Labels: HW

#386 [rtl] relocate TWI tri-state drivers
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_twi.vhd
Labels: HW

#387 [rtl] optimize instruction fetch
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: HW, optimization

#388 [rtl/PWM] minor cleanup
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_pwm.vhd
Labels: HW

#389 🔒 [TRNG] add read data security feature
  CHANGELOG.md
  docs/datasheet/soc_trng.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_trng.vhd
  sw/lib/source/neorv32_trng.c
Labels: enhancement, HW

#391 🚀 [sw] Update software framework to GCC 12.1.0
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
  sw/common/neorv32.ld
  sw/example/demo_freeRTOS/makefile
  sw/lib/source/syscalls.c
  sw/ocd-firmware/debug_rom.ld
  sw/ocd-firmware/makefile
Labels: SW

#397 [sw} cleanup crt0 start-up code
  CHANGELOG.md
  docs/datasheet/software.adoc
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  sw/common/crt0.S
Labels: SW

#398 [rtl] core cleanup / minor fixes
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, HW, optimization

#400 🚀 [docs] add neorv32-verilog repository
  README.md
  docs/datasheet/overview.adoc
  docs/userguide/content.adoc
  docs/userguide/neorv32_in_verilog.adoc
Labels: DOC, enhancement, experimental
