Repository stnolting/neorv32, pull requests merged in 2022-10, with the labels that each got.

#424 🐛 [.github] disable Windows/MSYS2 workflows for now
  .github/workflows/Processor.yml
Labels: bug, SW

#423 Fix Critical Warning in Quartus 20.1.0: avoid power up to high
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, optimization

#425 litex_core_complex: Expose configuration constants as generics.
  rtl/system_integration/neorv32_litex_core_complex.vhd
Labels: HW

#426 Add HW reset to CPU counter CSRs
  CHANGELOG.md
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sw/common/crt0.S
Labels: HW

#428 :bug: [rtl] fix is_power_of_two VHDL function
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
Labels: bug, HW

#431 :bug: [sw/lib] fix UART "char_received" function
  sw/lib/source/neorv32_uart.c
Labels: bug, SW

#433 [rtl] Optimize UART RTS behavior
  CHANGELOG.md
  docs/datasheet/soc_uart.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_uart.vhd
Labels: HW, optimization

#434 [rtl] Try to fix Quartus latch warnings
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, experimental

#436 ✨ [sw] add assembly-only demo program
  sw/example/demo_blink_led_asm/main.S
  sw/example/demo_blink_led_asm/makefile
Labels: SW
