Repository stnolting/neorv32, pull requests merged in 2022-12, with the labels that each got.

#447 [rtl] cleanup main package file
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
Labels: HW, coding-style

#448 [sw] rework intrinsic libraries
  sw/example/bitmanip_test/README.md
  sw/example/bitmanip_test/neorv32_b_extension_intrinsics.h
  sw/example/floating_point_test/README.md
  sw/example/floating_point_test/neorv32_zfinx_extension_intrinsics.h
  sw/lib/include/neorv32_cpu_cfu.h
  sw/lib/include/neorv32_intrinsics.h
Labels: riscv-compliance, SW

#449 ✨ Add CFU R4-type instructions
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_cfu.adoc
  docs/figures/cfu_r2type_instruction.png
  docs/figures/cfu_r3type_instruction.png
  docs/figures/cfu_r4type_instruction.png
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_cfu.vhd
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_cpu_regfile.vhd
  rtl/core/neorv32_package.vhd
  sw/example/demo_cfu/main.c
  sw/lib/include/neorv32_cpu_cfu.h
Labels: enhancement, HW, SW

#450 🐛 [rtl] core trap fixes
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_cfu.adoc
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sw/example/processor_check/main.c
  sw/lib/source/neorv32_cpu.c
Labels: bug, riscv-compliance, HW

#451 [sw] Remove B ISA extension intrinsic library
  README.md
  docs/datasheet/cpu.adoc
  sw/example/bitmanip_test/README.md
  sw/example/bitmanip_test/main.c
  sw/example/bitmanip_test/makefile
  sw/example/bitmanip_test/neorv32_b_extension_intrinsics.h
Labels: riscv-compliance, SW

#452 ✨ [CFU] add support for custom R5-type instructions
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_cfu.adoc
  docs/figures/cfu_r5type_instruction_a.png
  docs/figures/cfu_r5type_instruction_b.png
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_cfu.vhd
  rtl/core/neorv32_cpu_regfile.vhd
  rtl/core/neorv32_package.vhd
  sw/example/demo_cfu/main.c
  sw/lib/include/neorv32_cpu_cfu.h
  sw/lib/include/neorv32_intrinsics.h
Labels: enhancement, HW, SW

#456 🧪 [OCD] optimize firmware (park-loop)
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/on_chip_debugger.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/ocd-firmware/README.md
  sw/ocd-firmware/debug_rom.ld
  sw/ocd-firmware/park_loop.S
Labels: enhancement, HW, experimental

#457 🐛 [rtl] fix iCache block error bug
  CHANGELOG.md
  docs/datasheet/soc_icache.adoc
  rtl/core/neorv32_icache.vhd
  rtl/core/neorv32_package.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/processor_check/main.c
Labels: bug, HW

#461 [rt] SoC: rework r/w access logic and reset
  CHANGELOG.md
  docs/datasheet/soc.adoc
  rtl/core/neorv32_bus_keeper.vhd
  rtl/core/neorv32_cfs.vhd
  rtl/core/neorv32_gpio.vhd
  rtl/core/neorv32_gptmr.vhd
  rtl/core/neorv32_mtime.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_onewire.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_pwm.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_uart.vhd
  rtl/core/neorv32_wishbone.vhd
  rtl/core/neorv32_xip.vhd
  rtl/core/neorv32_xirq.vhd
Labels: HW, coding-style

#462 [rtl] CPU: optimizations and cleanup
  CHANGELOG.md
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_bus.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_cpu_cp_cfu.vhd
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, optimization, coding-style

#464 Remove signal initalizations
  CHANGELOG.md
  docs/datasheet/soc.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: HW, optimization

#463 Upgrade on-chip-debugger
  CHANGELOG.md
  docs/datasheet/on_chip_debugger.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/figures/address_space.png
  docs/references/riscv-debug-release.pdf
  docs/references/riscv-debug-stable.pdf
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_debug_dtm.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/lib/include/neorv32.h
  sw/ocd-firmware/park_loop.S
Labels: riscv-compliance, HW, optimization

#465 ⚠️ rework CPU debug spec ISA configuration; ✨ enhance trigger module
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/on_chip_debugger.adoc
  docs/datasheet/soc.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/example/demo_trigger_module/main.c
  sw/example/demo_trigger_module/makefile
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_rte.c
Labels: enhancement, riscv-compliance, HW

#467 [sw] rename library functions
  docs/datasheet/software.adoc
  docs/datasheet/software_rte.adoc
  rtl/core/neorv32_bootloader_image.vhd
  sw/bootloader/bootloader.c
  sw/example/demo_freeRTOS/main.c
  sw/example/demo_gptmr/main.c
  sw/example/demo_mtime/main.c
  sw/example/demo_onewire/main.c
  sw/example/demo_slink/main.c
  sw/example/demo_spi_irq/main.c
  sw/example/demo_wdt/main.c
  sw/example/floating_point_test/main.c
  sw/example/hello_cpp/main.cpp
  sw/example/hello_world/main.c
  sw/example/processor_check/main.c
  sw/lib/include/legacy.h
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_cpu_cfu.h
  sw/lib/include/neorv32_rte.h
  sw/lib/include/neorv32_uart.h
  sw/lib/source/neorv32_rte.c
  sw/lib/source/neorv32_uart.c
  sw/lib/source/neorv32_xirq.c
  sw/lib/source/syscalls.c
Labels: SW, coding-style
