Repository stnolting/neorv32, pull requests merged in 2022-05, with the labels that each got.

#311 update to new neoTRNG v2
  CHANGELOG.md
  docs/datasheet/soc_trng.adoc
  docs/userguide/simulating_the_processor.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_trng.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/demo_trng/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_trng.h
  sw/lib/source/neorv32_trng.c
Labels: enhancement, HW

#312 Cleanup bitmanip co-processor
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, optimization

#315 :bug: fix buskeeper timeout error
  CHANGELOG.md
  rtl/core/neorv32_bus_keeper.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, HW

#316 [TRNG] add optional/configurable data FIFO
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_trng.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_trng.vhd
  rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_trng.h
  sw/lib/source/neorv32_trng.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#318 crt0.S: Do not clear XIP control registers except in bootloader mode
  docs/datasheet/soc.adoc
  docs/datasheet/software.adoc
  sw/common/crt0.S
Labels: enhancement, SW

#323 [linker script, crt0] align all sections to 32-bit boundaries
  docs/datasheet/software.adoc
  sw/common/crt0.S
  sw/common/neorv32.ld
Labels: SW, optimization

#324 Constructors
  docs/datasheet/software.adoc
  sw/common/crt0.S
  sw/common/neorv32.ld
  sw/example/hello_cpp/main.cpp
  sw/example/hello_cpp/makefile
Labels: enhancement, SW

#327 🐛 Fix sync. vs. async. exception collision
  CHANGELOG.md
  docs/userguide/debugging_with_ocd.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sw/example/processor_check/main.c
Labels: bug, HW

#321 rework bootloader's SPI flash access
  CHANGELOG.md
  docs/datasheet/software_bootloader.adoc
  docs/userguide/customizing_the_bootloader.adoc
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  sw/bootloader/bootloader.c
Labels: enhancement, SW

#313 Bugfix - eliminates potential shift of data by 4 bytes.
  sw/common/crt0.S
  sw/common/neorv32.ld
Labels: bug, SW
