Repository stnolting/neorv32, pull requests merged in 2022-01, with the labels that each got.

#244 ✨ Add Execute In Place (XIP) Module
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_buskeeper.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/soc_wishbone.adoc
  docs/datasheet/soc_xip.adoc
  docs/datasheet/software.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_bus_keeper.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_wishbone.vhd
  rtl/core/neorv32_xip.vhd
  rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  setups/radiant/UPduino_v3/neorv32_upduino_v3.rdf
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/demo_xip/main.c
  sw/example/demo_xip/makefile
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_xip.h
  sw/lib/source/neorv32_rte.c
  sw/lib/source/neorv32_xip.c
  sw/svd/neorv32.svd
Labels: enhancement, HW, SW

#246 [rtl/core/mem] Rename legacy-style memory files
  rtl/core/mem/README.md
  rtl/core/mem/neorv32_dmem.legacy.vhd
  rtl/core/mem/neorv32_imem.legacy.vhd
Labels: HW

#248 [.github/riscv-arch-test] Fix / rework
  .github/workflows/riscv-arch-test.yml
  docs/datasheet/cpu.adoc
  sim/run_riscv_arch_test.sh
  sim/simple/neorv32_imem.simple.vhd
Labels: CI

#247 [BUSKEEPER] Add NULL address check option
  CHANGELOG.md
  docs/datasheet/soc_buskeeper.adoc
  rtl/core/neorv32_bus_keeper.vhd
  rtl/core/neorv32_cpu_bus.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/lib/include/neorv32.h
  sw/svd/neorv32.svd
Labels: HW

#249 :warning: [XIP] reworked execute in place module
  CHANGELOG.md
  docs/datasheet/overview.adoc
  docs/datasheet/soc_xip.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_xip.vhd
  sw/example/demo_xip/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_xip.h
  sw/lib/source/neorv32_xip.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#251 [SPI & XIP] add high-speed SPI mode option
  CHANGELOG.md
  docs/datasheet/soc_spi.adoc
  docs/datasheet/soc_xip.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_xip.vhd
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_spi.h
  sw/lib/include/neorv32_xip.h
  sw/lib/source/neorv32_spi.c
  sw/lib/source/neorv32_xip.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#252 setups/osflow/synthesis: recent versions of yosys need command 'read_verilog'
  setups/osflow/synthesis.mk
Labels: bug, CI

#253 🐛 [BUSKEEPER] fix bug in error flag logic
  CHANGELOG.md
  docs/datasheet/soc_buskeeper.adoc
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bus_keeper.vhd
  rtl/core/neorv32_package.vhd
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_rte.c
  sw/svd/neorv32.svd
Labels: bug, HW

#255 [GPIO] raise bus exception if writing to INPUT registers
  CHANGELOG.md
  docs/datasheet/soc_gpio.adoc
  rtl/core/neorv32_gpio.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/lib/include/neorv32.h
Labels: enhancement, HW

#256 [rtl/core] rework CPU issue engine (area optimization)
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: enhancement, HW

#258 [DOC] User Guide - 1.3. Installation
  docs/userguide/sw_toolchain_setup.adoc
Labels: DOC

#259 [B ISA extension] add single-bit instructions (Zbs) support
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_package.vhd
  sw/example/bitmanip_test/main.c
  sw/example/bitmanip_test/neorv32_b_extension_intrinsics.h
Labels: enhancement, riscv-compliance, HW, SW

#260 [B ISA extension] add carry-less multiply instructions (Zbc) support
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_package.vhd
  sw/example/bitmanip_test/main.c
  sw/example/bitmanip_test/neorv32_b_extension_intrinsics.h
Labels: enhancement, riscv-compliance, HW, SW

#261 [CFS] add demo program
  CHANGELOG.md
  docs/datasheet/soc_cfs.adoc
  rtl/core/neorv32_cfs.vhd
  rtl/core/neorv32_package.vhd
  sw/example/demo_cfs/main.c
  sw/example/demo_cfs/makefile
Labels: DOC, SW

#262 [rtl/core] add 4 additional CPU CP slots; fix bugs in CP arbitration logic
  CHANGELOG.md
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_cpu_cp_shifter.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, HW
