Repository stnolting/neorv32, pull requests merged in 2022-03, with the labels that each got.

#282 Update neorv32_gptmr.c
  sw/lib/source/neorv32_gptmr.c
Labels: DOC

#283 🐛 [PMP] fix pmpaddr CSR layout
  CHANGELOG.md
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/soc.adoc
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/example/demo_pmp/main.c
  sw/lib/source/neorv32_cpu.c
Labels: bug, riscv-compliance, HW, SW

#285 [rtl] CPU code clean-up; add RISC-V mstatus.TW CSR bit
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sw/common/crt0.S
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_cpu.h
  sw/lib/source/neorv32_cpu.c
Labels: riscv-compliance, HW

#286 Fix some typos.
  rtl/README.md
Labels: DOC

#289 [rtl] set mtval CSR to zero on ebreak instructions
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sim/run_riscv_arch_test.sh
  sw/isa-test/port-neorv32/README.md
  sw/isa-test/port-neorv32/model_test.h
  sw/isa-test/port-neorv32/riscv-test-suite/rv32i_m/C/references/cebreak-01.reference_output
  sw/isa-test/port-neorv32/riscv-test-suite/rv32i_m/privilege/references/ebreak.reference_output
Labels: riscv-compliance, HW

#290 🧪 try to fix *_reduce_f functions usage for gate-level simulation
  CHANGELOG.md
  rtl/core/neorv32_cpu_bus.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_cpu_cp_shifter.vhd
  rtl/core/neorv32_cpu_regfile.vhd
  rtl/core/neorv32_icache.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_xirq.vhd
Labels: experimental
