Repository stnolting/neorv32, pull requests merged in 2023-09, with the labels that each got.

#679 minor rtl edits and cleanups
  CHANGELOG.md
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_cpu_cp_shifter.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_cpu_regfile.vhd
  rtl/core/neorv32_crc.vhd
  rtl/core/neorv32_intercon.vhd
  rtl/core/neorv32_package.vhd
Labels: HW

#680 [cpu] add execution monitor
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: enhancement, HW

#681 [CFU] add support for CFU-internal CSRs
  CHANGELOG.md
  docs/datasheet/cpu_cfu.adoc
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_cfu.vhd
  rtl/core/neorv32_package.vhd
  sw/example/demo_cfu/main.c
  sw/lib/include/neorv32_cpu_cfu.h
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_cpu_cfu.c
  sw/openocd/openocd_neorv32.cfg
Labels: enhancement, HW

#683 CPU hardware optimization
  CHANGELOG.md
  docs/datasheet/on_chip_debugger.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sw/lib/include/neorv32_cpu_csr.h
Labels: HW, optimization

#684 minor rtl edits
  CHANGELOG.md
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_crc.vhd
  rtl/core/neorv32_dcache.vhd
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_gpio.vhd
  rtl/core/neorv32_icache.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_pwm.vhd
  rtl/core/neorv32_sdi.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_uart.vhd
  rtl/core/neorv32_wdt.vhd
  rtl/core/neorv32_xirq.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
Labels: HW

#690 Minor rtl edits
  CHANGELOG.md
  docs/datasheet/cpu_cfu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/references/riscv-smcntrpmf-v1.0.pdf
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_cfu.vhd
  rtl/core/neorv32_package.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  sw/example/demo_cfu/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu_cfu.h
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_cpu_cfu.c
Labels: HW

#692 rework watchdog timer and reset system
  CHANGELOG.md
  docs/datasheet/on_chip_debugger.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_wdt.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_wdt.vhd
  sw/example/demo_wdt/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_wdt.h
  sw/lib/source/neorv32_wdt.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#691 implement vectored `mtvec`
  CHANGELOG.md
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sim/neorv32_tb.vhd
  sw/example/processor_check/main.c
Labels: enhancement, risc-v compliance, HW

#694 Minor rtl optimizations and cleanups
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_gpio.vhd
  rtl/core/neorv32_intercon.vhd
  rtl/core/neorv32_onewire.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_wdt.vhd
Labels: HW, optimization

#695 [PMP] logic optimization
  CHANGELOG.md
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, optimization
