Repository stnolting/neorv32, pull requests merged in 2023-08, with the labels that each got.

#665 [rtl] fix natural condition
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, HW

#670 Remove Zicond ISA extension
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_cond.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/zicond_test/README.md
  sw/example/zicond_test/main.c
  sw/example/zicond_test/makefile
  sw/example/zicond_test/zicond_intrinsics.h
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_rte.c
Labels: risc-v compliance, HW

#672 [rtl] minor edits and cleanups
  CHANGELOG.md
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/software_rte.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_intercon.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/lib/source/neorv32_cpu.c
Labels: HW

#673 Update RTE to support easy emulation of instructions
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/software_rte.adoc
  rtl/core/neorv32_package.vhd
  sw/example/demo_emulate_unaligned/main.c
  sw/example/demo_emulate_unaligned/makefile
  sw/lib/include/neorv32_rte.h
  sw/lib/source/neorv32_rte.c
Labels: SW, experimental

#674 ⚠️ constrain MTVAL CSR, add MTINST CSR
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/software_rte.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sw/example/demo_emulate_unaligned/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_rte.c
Labels: enhancement, risc-v compliance, HW

#676 Add Smcntrpmf ISA extension
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sim/neorv32_tb.vhd
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_rte.c
Labels: enhancement, risc-v compliance, HW

#677 [OCD] add option to select DM legacy mode
  CHANGELOG.md
  docs/datasheet/on_chip_debugger.adoc
  docs/datasheet/soc.adoc
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_debug_dtm.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/ocd-firmware/park_loop.S
  sw/openocd/openocd_neorv32.cfg
Labels: enhancement, risc-v compliance, HW

#678 [cpu] remove branch prediction logic
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, optimization
