Repository stnolting/neorv32, pull requests merged in 2023-04, with the labels that each got.

#566 [PMP] add support for NA4 and NAPOT modes
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_cpu_bus.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sim/neorv32_tb.vhd
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu.h
  sw/lib/source/neorv32_cpu.c
  sw/lib/source/neorv32_rte.c
Labels: enhancement, riscv-compliance, HW

#569 [rtl] cleanups and optimizations
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_bus.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_cpu_cp_cfu.vhd
  rtl/core/neorv32_cpu_cp_cond.vhd
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_cpu_cp_shifter.vhd
  rtl/core/neorv32_cpu_decompressor.vhd
  rtl/core/neorv32_cpu_regfile.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sim/neorv32_tb.vhd
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_rte.c
Labels: HW

#570 update XIRQ controller
  CHANGELOG.md
  docs/datasheet/soc_xirq.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_xirq.vhd
  sw/example/demo_xirq/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_xirq.h
  sw/lib/source/neorv32_xirq.c
Labels: HW

#571 [rtl] coding style edits and cleanups
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_xip.vhd
Labels: HW, coding-style

#561 Remove warnings
  sw/lib/include/neorv32_rte.h
  sw/lib/source/neorv32_rte.c
  sw/lib/source/neorv32_uart.c
Labels: SW, coding-style

#574 Updated path for FreeRTOS example - FreeRTOS-Plus-TCP
  sw/example/demo_freeRTOS/makefile
Labels: SW

#578 🐛 FPU bug fix and rtl optimizations
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_bus.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sw/example/demo_xip/main.c
  sw/lib/include/neorv32_xip.h
  sw/lib/source/neorv32_xip.c
Labels: bug, HW, SW, optimization

#581 [UART] add FIFO configuration to DATA register
  CHANGELOG.md
  docs/datasheet/soc_uart.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_uart.vhd
  sw/lib/include/legacy.h
  sw/lib/include/neorv32_uart.h
  sw/lib/source/neorv32_uart.c
Labels: enhancement, HW

#586 🐛⚠️ CPU bug-fixes, major cleanups and optimizations
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/software.adoc
  docs/datasheet/software_rte.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_decompressor.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_xirq.vhd
  sim/neorv32_tb.vhd
  sw/common/crt0.S
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu.h
  sw/lib/source/neorv32_rte.c
Labels: bug, risc-v compliance, HW, SW, optimization, coding-style

#585 Freertos xirq example
  sw/example/demo_freeRTOS_xirq/FreeRTOSConfig.h
  sw/example/demo_freeRTOS_xirq/README.md
  sw/example/demo_freeRTOS_xirq/chip_specific_extensions/neorv32/freertos_risc_v_chip_specific_extensions.h
  sw/example/demo_freeRTOS_xirq/demo/main_demo.c
  sw/example/demo_freeRTOS_xirq/main.c
  sw/example/demo_freeRTOS_xirq/makefile
Labels: SW

#591 [rtl] minor optimizations/cleanups of processor bus system
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_bus.vhd
  rtl/core/neorv32_dcache.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: HW, optimization

#592 Added a test case to show the 1.0 + -1.0 instruction time-out under f…
  CHANGELOG.md
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_package.vhd
  sw/example/float_corner_test/main.c
Labels: bug, HW

#593 ✨ add optional direct memory access controller (DMA)
  CHANGELOG.md
  README.md
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_dma.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/software.adoc
  docs/figures/neorv32_bus.png
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_busswitch.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/demo_dma/main.c
  sw/example/demo_dma/makefile
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_dma.h
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_dma.c
  sw/lib/source/neorv32_rte.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#601 🐛 [rtl] fix bug in DMA
  CHANGELOG.md
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_package.vhd
  sim/neorv32_tb.vhd
Labels: bug, HW

#605 [rtl] minor edits; update to VUnit v5
  CHANGELOG.md
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_bus.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_dcache.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sim/run.py
Labels: HW
