Repository stnolting/neorv32, pull requests merged in 2023-02, with the labels that each got.

#483 💄 [docs] update/rework figures
  README.md
  docs/Doxyfile
  docs/attrs.adoc
  docs/attrs.main.adoc
  docs/datasheet/index.adoc
  docs/figures/neorv32_boot_configurations.png
  docs/figures/neorv32_bus.png
  docs/figures/neorv32_cpu.png
  docs/figures/neorv32_cpu_block.png
  docs/figures/neorv32_logo.png
  docs/figures/neorv32_logo_dark.png
  docs/figures/neorv32_logo_front.png
  docs/figures/neorv32_logo_riscv.png
  docs/figures/neorv32_logo_small.png
  docs/figures/neorv32_logo_smcard.jpg
  docs/figures/neorv32_logo_transparent.png
  docs/figures/neorv32_logo_transparent_small.png
  docs/figures/neorv32_memory_configurations.png
  docs/figures/neorv32_ocd_complex.png
  docs/figures/neorv32_processor.png
  docs/figures/neorv32_test_setup.png
  docs/userguide/index.adoc
Labels: DOC

#484 [rtl] Cleanup CPU interrupt controller
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: HW

#486 [rtl] rework mip csr
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sw/example/processor_check/main.c
Labels: riscv-compliance, HW

#487 [rtl] CPU control optimization
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, optimization

#489 [rtl] CPU: use record as main control bus type
  CHANGELOG.md
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_bus.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_cpu_cp_cfu.vhd
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_cpu_cp_shifter.vhd
  rtl/core/neorv32_cpu_decompressor.vhd
  rtl/core/neorv32_cpu_regfile.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, coding-style

#490 [rtl] add co-processor timing monitor
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_cfu.adoc
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: enhancement, HW

#493 [sw/lib/include/neorv32.h]: remove redundant uart typedef
  sw/lib/include/neorv32.h
Labels: SW, coding-style

#491 ⚠️ Replace IO_GPIO_EN generic
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_gpio.adoc
  rtl/core/neorv32_gpio.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd
  rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  rtl/test_setups/neorv32_test_setup_approm.vhd
  rtl/test_setups/neorv32_test_setup_bootloader.vhd
  rtl/test_setups/neorv32_test_setup_on_chip_debugger.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
Labels: HW

#497 [rtl] minor trap logic optimizations and fixes
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: HW

#494 Add run.py dump of VHDL-LS library mapping
  docs/userguide/content.adoc
  docs/userguide/vhdl_development_environment.adoc
  sim/run.py
Labels: CI

#496 [sw] add '_zicsr' to default MARCH configuration
  docs/datasheet/software.adoc
  docs/userguide/customizing_the_bootloader.adoc
  sw/common/common.mk
Labels: riscv-compliance, SW

#500 🐛 [rtl] fix bug in co-processor monitor
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_cfu.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  sw/example/demo_cfu/main.c
Labels: bug, HW

#501 ⚠️ constrain & relocate PWM module
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_pwm.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_pwm.vhd
  rtl/core/neorv32_top.vhd
  rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd
  rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/demo_pwm/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_pwm.h
  sw/lib/source/neorv32_pwm.c
  sw/svd/neorv32.svd
Labels: HW

#503 [CFS] add another 64 interface registers
  CHANGELOG.md
  docs/datasheet/soc_cfs.adoc
  rtl/core/neorv32_cfs.vhd
  rtl/core/neorv32_package.vhd
  sw/example/demo_cfs/main.c
  sw/lib/include/neorv32.h
Labels: enhancement, HW

#504 :warning: rename SPI & XIP module's top interface ports
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_spi.adoc
  docs/datasheet/soc_xip.adoc
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_xip.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
Labels: HW, coding-style

#505 ✨ add SDI module (SPI device-class interface)
  CHANGELOG.md
  README.md
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_sdi.adoc
  docs/datasheet/soc_spi.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/software.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sdi.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/demo_sdi/main.c
  sw/example/demo_sdi/makefile
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_sdi.h
  sw/lib/source/neorv32_rte.c
  sw/lib/source/neorv32_sdi.c
  sw/svd/neorv32.svd
Labels: enhancement, experimental

#511 GPTMR: Change "variable style" by "pointer style"
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_gptmr.c
Labels: SW, coding-style

#512 MTIME: Change "variable style" by "pointer style"
  sw/bootloader/bootloader.c
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_mtime.c
Labels: SW, coding-style

#513 NEOLED: Change "variable style" by "pointer style"
  sw/example/demo_neopixel/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_neoled.h
  sw/lib/source/neorv32_neoled.c
Labels: SW, coding-style

#510 GPIO: Change "variable style" by "pointer style"
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_gpio.c
Labels: SW, coding-style

#514 ONEWIRE: Change "variable style" by "pointer style"
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_onewire.c
Labels: SW, coding-style

#515 PWM: Change "variable style" by "pointer style"
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_pwm.c
Labels: SW, coding-style

#516 SDI: Change "variable style" by "pointer style"
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_sdi.c
Labels: SW, coding-style

#517 SPI: Change "variable style" by "pointer style"
  sw/example/demo_spi/main.c
  sw/example/demo_spi_irq/drv/neorv32_spi_irq.c
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_spi.c
Labels: SW, coding-style

#518 TRNG: Change "variable style" by "pointer style"
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_trng.c
Labels: SW, coding-style

#519 TWI: Change "variable style" by "pointer style"
  sw/example/demo_twi/main.c
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_twi.c
Labels: SW, coding-style

#520 WDT: Change "variable style" by "pointer style"
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_wdt.c
Labels: SW, coding-style

#521 XIP: Change "variable style" by "pointer style"
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_xip.c
Labels: SW, coding-style

#526 SYSINFO: Change "variable style" by "pointer style"
  sw/bootloader/bootloader.c
  sw/example/coremark/core_portme.c
  sw/example/demo_freeRTOS/main.c
  sw/example/demo_gptmr/main.c
  sw/example/demo_mtime/main.c
  sw/example/demo_newlib/main.c
  sw/example/demo_spi/main.c
  sw/example/demo_twi/main.c
  sw/example/demo_wdt/main.c
  sw/example/demo_xip/main.c
  sw/example/dhrystone/dhry_1.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_cfs.c
  sw/lib/source/neorv32_cpu.c
  sw/lib/source/neorv32_gpio.c
  sw/lib/source/neorv32_gptmr.c
  sw/lib/source/neorv32_mtime.c
  sw/lib/source/neorv32_neoled.c
  sw/lib/source/neorv32_onewire.c
  sw/lib/source/neorv32_pwm.c
  sw/lib/source/neorv32_rte.c
  sw/lib/source/neorv32_sdi.c
  sw/lib/source/neorv32_spi.c
  sw/lib/source/neorv32_trng.c
  sw/lib/source/neorv32_twi.c
  sw/lib/source/neorv32_uart.c
  sw/lib/source/neorv32_wdt.c
  sw/lib/source/neorv32_xip.c
  sw/lib/source/neorv32_xirq.c
Labels: SW, coding-style
