Repository stnolting/neorv32, pull requests merged in 2023-01, with the labels that each got.

#468 [rtl] OCD: update DTM and DM
  CHANGELOG.md
  docs/datasheet/on_chip_debugger.adoc
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_debug_dtm.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: riscv-compliance, HW, experimental, optimization

#469 Fix value of SYSINFO_SOC_IO_ONEWIRE in NEORV32_SYSINFO_SOC_enum
  sw/lib/include/neorv32.h
Labels: bug, SW

#470 [rtl] CPU: logic optimization
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, optimization

#471 [sw/example/demo_spi_irq]: make read/write data pointer and busy flag…
  sw/example/demo_spi_irq/drv/neorv32_spi_irq.c
  sw/example/demo_spi_irq/drv/neorv32_spi_irq.h
Labels: SW, optimization

#472 [rtl] update TRNG
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_trng.vhd
Labels: HW

#474 :warning: rework watchdog timer (WDT)
  CHANGELOG.md
  docs/datasheet/soc_wdt.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_wdt.vhd
  sw/example/demo_wdt/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_wdt.h
  sw/lib/source/neorv32_wdt.c
Labels: enhancement, HW

#476 [rtl] VHDL cleanups
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_fifo.vhd
  rtl/core/neorv32_mtime.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: HW, coding-style

#477 :warning: Rework CPU counters
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_mtime.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_fifo.vhd
  rtl/core/neorv32_mtime.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd
  rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_ProcessorTop_stdlogic.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/processor_check/main.c
  sw/lib/include/legacy.h
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_cpu.h
  sw/lib/source/neorv32_cpu.c
Labels: riscv-compliance, HW, optimization, coding-style

#478 [sw] cleanup and update software framework
  CHANGELOG.md
  docs/datasheet/software.adoc
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  sw/bootloader/bootloader.c
  sw/common/crt0.S
  sw/example/bus_explorer/main.c
  sw/example/coremark/core_portme.c
  sw/example/demo_gptmr/main.c
  sw/example/demo_mtime/main.c
  sw/example/demo_slink/main.c
  sw/example/demo_spi_irq/main.c
  sw/example/demo_trigger_module/main.c
  sw/example/demo_wdt/main.c
  sw/example/demo_xirq/main.c
  sw/example/dhrystone/dhry_1.c
  sw/example/hello_cpp/main.cpp
  sw/example/processor_check/main.c
  sw/lib/include/legacy.h
  sw/lib/include/neorv32_cpu.h
  sw/lib/source/neorv32_cpu.c
  sw/lib/source/neorv32_xirq.c
Labels: SW, optimization
