Repository stnolting/neorv32, pull requests merged in 2023-03, with the labels that each got.

#528 Added test case in sw/example to demonstrate floating point normalize…
  CHANGELOG.md
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_package.vhd
  sw/example/float_corner_test/README.md
  sw/example/float_corner_test/main.c
  sw/example/float_corner_test/makefile
  sw/example/float_corner_test/neorv32_zfinx_extension_intrinsics.h
Labels: bug, HW, optimization

#529 [rtl] minor GPTMR code reworks
  CHANGELOG.md
  docs/datasheet/soc_gptmr.adoc
  rtl/core/neorv32_gptmr.vhd
  rtl/core/neorv32_package.vhd
  sw/example/demo_gptmr/main.c
Labels: HW

#509 Common neorv32 uart functions
  sw/example/processor_check/main.c
  sw/lib/include/legacy.h
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_uart.h
  sw/lib/source/neorv32_uart.c
Labels: SW, coding-style

#531 [sw/uart] allow for escaped percent sign
  sw/lib/source/neorv32_uart.c
Labels: enhancement, SW

#530 :warning: Update / rework SPI module
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_spi.adoc
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  sw/bootloader/bootloader.c
  sw/example/demo_spi/main.c
  sw/example/demo_spi_irq/drv/neorv32_spi_irq.c
  sw/example/demo_spi_irq/drv/neorv32_spi_irq.h
  sw/example/demo_spi_irq/main.c
  sw/example/processor_check/main.c
  sw/lib/include/legacy.h
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_cpu.h
  sw/lib/include/neorv32_spi.h
  sw/lib/source/neorv32_cpu.c
  sw/lib/source/neorv32_spi.c
  sw/svd/neorv32.svd
Labels: HW, optimization

#532 SVD: Corrected typo
  sw/svd/neorv32.svd
Labels: bug, SW

#533 ⚠️ rework UART modules
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_spi.adoc
  docs/datasheet/soc_uart.adoc
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_uart.vhd
  rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/bootloader/bootloader.c
  sw/example/bus_explorer/main.c
  sw/example/coremark/core_portme.c
  sw/example/demo_cfs/main.c
  sw/example/demo_cfu/main.c
  sw/example/demo_freeRTOS/main.c
  sw/example/demo_gptmr/main.c
  sw/example/demo_hpm/main.c
  sw/example/demo_mtime/main.c
  sw/example/demo_neopixel/main.c
  sw/example/demo_newlib/main.c
  sw/example/demo_onewire/main.c
  sw/example/demo_pmp/main.c
  sw/example/demo_pwm/main.c
  sw/example/demo_sdi/main.c
  sw/example/demo_spi/main.c
  sw/example/demo_spi_irq/main.c
  sw/example/demo_trigger_module/main.c
  sw/example/demo_trng/main.c
  sw/example/demo_twi/main.c
  sw/example/demo_wdt/main.c
  sw/example/demo_xip/main.c
  sw/example/demo_xirq/main.c
  sw/example/dhrystone/dhry_1.c
  sw/example/float_corner_test/main.c
  sw/example/floating_point_test/main.c
  sw/example/game_of_life/main.c
  sw/example/hardware_info/main.c
  sw/example/hello_cpp/main.cpp
  sw/example/hello_world/main.c
  sw/example/processor_check/main.c
  sw/lib/include/legacy.h
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_uart.h
  sw/lib/source/neorv32_uart.c
  sw/svd/neorv32.svd
Labels: HW, SW

#536 Update NEOLED module
  CHANGELOG.md
  docs/datasheet/soc_neoled.adoc
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/example/demo_neopixel/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_neoled.h
  sw/lib/source/neorv32_neoled.c
Labels: HW, SW

#541 [UART] re-integrate RTS/CTS hardware flow-control
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_uart.adoc
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_uart.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/lib/include/legacy.h
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_uart.h
  sw/lib/source/neorv32_uart.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#543 [rtl] move ONEWIRE and TWI tri-state drivers out of core
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_onewire.adoc
  docs/datasheet/soc_twi.adoc
  docs/userguide/packaging_vivado.adoc
  rtl/core/neorv32_onewire.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_twi.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
Labels: enhancement, HW

#545 [rtl] minor edits, cleanups and optimization
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_bus_keeper.vhd
  rtl/core/neorv32_busswitch.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_decompressor.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_wdt.vhd
  rtl/core/neorv32_xirq.vhd
Labels: HW, optimization

#546 ✨ add support for RISC-V 'Zicond' ISA extension
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/figures/neorv32_cpu_block.png
  docs/figures/neorv32_processor.png
  docs/references/riscv-zicond_1.0-rc1.pdf
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_cond.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/zicond_test/README.md
  sw/example/zicond_test/main.c
  sw/example/zicond_test/makefile
  sw/example/zicond_test/zicond_intrinsics.h
  sw/lib/include/neorv32.h
  sw/lib/source/neorv32_rte.c
Labels: enhancement, riscv-compliance

#549 [docs] rework, update and cleanup entire documentation
  README.md
  docs/attrs.adoc
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_cfu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/on_chip_debugger.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/rationale.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_bootrom.adoc
  docs/datasheet/soc_buskeeper.adoc
  docs/datasheet/soc_cfs.adoc
  docs/datasheet/soc_dmem.adoc
  docs/datasheet/soc_gpio.adoc
  docs/datasheet/soc_gptmr.adoc
  docs/datasheet/soc_icache.adoc
  docs/datasheet/soc_mtime.adoc
  docs/datasheet/soc_neoled.adoc
  docs/datasheet/soc_onewire.adoc
  docs/datasheet/soc_pwm.adoc
  docs/datasheet/soc_sdi.adoc
  docs/datasheet/soc_spi.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/soc_trng.adoc
  docs/datasheet/soc_twi.adoc
  docs/datasheet/soc_uart.adoc
  docs/datasheet/soc_wdt.adoc
  docs/datasheet/soc_wishbone.adoc
  docs/datasheet/soc_xip.adoc
  docs/datasheet/soc_xirq.adoc
  docs/datasheet/software.adoc
  docs/datasheet/software_bootloader.adoc
  docs/datasheet/software_rte.adoc
Labels: DOC

#551 Added support for USER_LIBS in the command SW makefile.
  docs/datasheet/software.adoc
  sw/common/common.mk
Labels: enhancement, SW

#552 [sw] bootloader: send wake up command to flash before trying to speak with it
  docs/datasheet/software_bootloader.adoc
  rtl/core/neorv32_bootloader_image.vhd
  sw/bootloader/bootloader.c
Labels: enhancement, SW

#550 [rtl] reworks, cleanups and optimizations
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_fifo.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sdi.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_uart.vhd
Labels: HW, optimization

#553 [sw/lib] move CSR definitions to separate file
  docs/datasheet/soc_bootrom.adoc
  docs/datasheet/software.adoc
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_cpu_csr.h
Labels: SW

#555 [rtl] re-add VHDL process names
  CHANGELOG.md
  rtl/core/neorv32_bus_keeper.vhd
  rtl/core/neorv32_cpu_cp_cond.vhd
  rtl/core/neorv32_cpu_decompressor.vhd
  rtl/core/neorv32_fifo.vhd
  rtl/core/neorv32_gpio.vhd
  rtl/core/neorv32_gptmr.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_onewire.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_pwm.vhd
  rtl/core/neorv32_sdi.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_uart.vhd
  rtl/core/neorv32_wdt.vhd
  rtl/core/neorv32_xirq.vhd
Labels: HW, coding-style

#556 ✨ add time[h] CSRs
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sim/neorv32_tb.vhd
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu_csr.h
Labels: riscv-compliance, HW

#557 [rtl] cleanup top's generics
  CHANGELOG.md
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/on_chip_debugger.adoc
  docs/datasheet/soc.adoc
  docs/userguide/debugging_with_ocd.adoc
  rtl/core/neorv32_cfs.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd
  rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/openocd/openocd_neorv32.cfg
Labels: HW

#560 🧪 Add processor data cache
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_dcache.adoc
  docs/datasheet/soc_icache.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/figures/neorv32_bus.png
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_dcache.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_rte.c
Labels: enhancement, HW, experimental, optimization

#562 ⚠️ [rtl] remove Zicsr generic, cleanups and optimizations
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/soc.adoc
  rtl/core/neorv32_busswitch.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_dcache.vhd
  rtl/core/neorv32_icache.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd
  rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
  rtl/test_setups/neorv32_test_setup_approm.vhd
  rtl/test_setups/neorv32_test_setup_bootloader.vhd
  rtl/test_setups/neorv32_test_setup_on_chip_debugger.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
Labels: HW, optimization

#565 Bootloader Config Parameter to Enable UART0 HW Handshaking.
  docs/datasheet/soc_dcache.adoc
  docs/userguide/customizing_the_bootloader.adoc
  sw/bootloader/bootloader.c
Labels: enhancement, SW
