Repository stnolting/neorv32, pull requests merged in 2023-06, with the labels that each got.

#626 🐛 [linker script] fix section continuity issue
  CHANGELOG.md
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  sw/bootloader/bootloader.c
  sw/common/neorv32.ld
Labels: bug, SW

#627 [SYSINFO] re-arrange bits
  CHANGELOG.md
  docs/datasheet/soc_sysinfo.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  sw/lib/include/neorv32_sysinfo.h
  sw/svd/neorv32.svd
Labels: HW, SW

#628 ✨ Re-add simplified stream link interface (SLINK)
  CHANGELOG.md
  README.md
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_slink.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/software.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/demo_slink/main.c
  sw/example/demo_slink/makefile
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_slink.h
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_rte.c
  sw/lib/source/neorv32_slink.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#632 :sparkles: add CRC unit
  CHANGELOG.md
  README.md
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_crc.adoc
  docs/datasheet/soc_dma.adoc
  docs/datasheet/soc_pwm.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/software.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_crc.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/demo_crc/main.c
  sw/example/demo_crc/makefile
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_crc.h
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_crc.c
  sw/lib/source/neorv32_rte.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#634 [makefile] extend GDB target
  docs/datasheet/software.adoc
  docs/userguide/debugging_with_ocd.adoc
  sw/common/common.mk
Labels: enhancement, SW

#635 ⚠️ remove BUSKEEPER's status register
  CHANGELOG.md
  docs/datasheet/soc_buskeeper.adoc
  docs/datasheet/software_rte.adoc
  rtl/core/neorv32_bus_keeper.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_buskeeper.h
  sw/lib/source/neorv32_rte.c
  sw/svd/neorv32.svd
Labels: HW

#636 optimize CPU's control logic
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, optimization

#637 🧪 VHDL - use entity instantiation
  CHANGELOG.md
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sdi.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_uart.vhd
Labels: HW, experimental, coding-style

#639 demo_blink_led_asm bugfix
  docs/datasheet/soc.adoc
  sw/example/demo_blink_led_asm/main.S
Labels: bug, SW

#641 Minor rtl edits, cleanups and optimizations
  CHANGELOG.md
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_wishbone.vhd
Labels: HW
