Repository stnolting/neorv32, pull requests merged in 2023-10, with the labels that each got.

#696 [SW] Warning removed of unused variable
  sw/lib/include/neorv32_cpu.h
Labels: SW

#697 :warning: rework SoC bus protocol
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/figures/bus_interface.png
  docs/figures/bus_interface_atomic.png
  docs/sources/bus_interface.json
  docs/sources/bus_interface_atomic.json
  rtl/core/mem/neorv32_dmem.default.vhd
  rtl/core/mem/neorv32_dmem.legacy.vhd
  rtl/core/mem/neorv32_imem.default.vhd
  rtl/core/mem/neorv32_imem.legacy.vhd
  rtl/core/neorv32_boot_rom.vhd
  rtl/core/neorv32_cfs.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_crc.vhd
  rtl/core/neorv32_dcache.vhd
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_gpio.vhd
  rtl/core/neorv32_gptmr.vhd
  rtl/core/neorv32_icache.vhd
  rtl/core/neorv32_intercon.vhd
  rtl/core/neorv32_mtime.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_onewire.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_pwm.vhd
  rtl/core/neorv32_sdi.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_uart.vhd
  rtl/core/neorv32_wdt.vhd
  rtl/core/neorv32_wishbone.vhd
  rtl/core/neorv32_xip.vhd
  rtl/core/neorv32_xirq.vhd
Labels: HW, optimization

#698 [SW] Illegal instruction removed
  sw/example/coremark/core_portme.c
Labels: SW

#699 [dma] add "transfer done" flag
  CHANGELOG.md
  docs/datasheet/soc_dma.adoc
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_package.vhd
  sw/example/demo_dma/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_dma.h
  sw/lib/source/neorv32_dma.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#702 Update correct file
  docs/userguide/executable_upload.adoc
Labels: DOC

#703 minor edits and optimizations
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_intercon.vhd
  rtl/core/neorv32_package.vhd
  sim/neorv32_tb.vhd
  sw/example/processor_check/main.c
Labels: HW, SW

#704 Match existing filename
  docs/userguide/simulating_the_processor.adoc
Labels: DOC

#705 Update software framework to gcc-13.2.0
  .github/workflows/Processor.yml
  CHANGELOG.md
  do.py
  docs/datasheet/software.adoc
  rtl/core/neorv32_package.vhd
  sw/common/common.mk
  sw/example/demo_freeRTOS/makefile
  sw/example/demo_freeRTOS_xirq/makefile
  sw/example/processor_check/run_check.sh
  sw/ocd-firmware/makefile
Labels: SW

#707 [cpu] minor cleanups and optimizations
  CHANGELOG.md
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_regfile.vhd
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_wdt.vhd
  sw/example/processor_check/main.c
Labels: HW, optimization

#709 ⚠️ remove Zifencei generic - Zifencei ISA extension is now always enabled
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/soc.adoc
  docs/userguide/customizing_the_bootloader.adoc
  docs/userguide/debugging_with_ocd.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
  rtl/test_setups/neorv32_test_setup_on_chip_debugger.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/processor_check/main.c
Labels: HW

#711 [sw/lib] add nerov32-flavored vprintf funtion
  sw/lib/include/neorv32_uart.h
  sw/lib/source/neorv32_uart.c
Labels: enhancement, SW

#715 [sim] Add GHDL run flags variable
  docs/datasheet/software.adoc
  sim/simple/ghdl.run.sh
  sim/simple/ghdl.sh
  sw/common/common.mk
Labels: SW

#716 Move FreeRTOS port & demo into new repository
  CHANGELOG.md
  README.md
  docs/datasheet/software.adoc
  docs/userguide/free_rtos_support.adoc
  rtl/core/neorv32_package.vhd
  sw/example/demo_freeRTOS/FreeRTOSConfig.h
  sw/example/demo_freeRTOS/README.md
  sw/example/demo_freeRTOS/blinky_demo/main_blinky.c
  sw/example/demo_freeRTOS/chip_specific_extensions/neorv32/freertos_risc_v_chip_specific_extensions.h
  sw/example/demo_freeRTOS/full_demo/RegTest.s
  sw/example/demo_freeRTOS/full_demo/main_full.c
  sw/example/demo_freeRTOS/main.c
  sw/example/demo_freeRTOS/makefile
  sw/example/demo_freeRTOS_xirq/FreeRTOSConfig.h
  sw/example/demo_freeRTOS_xirq/README.md
  sw/example/demo_freeRTOS_xirq/chip_specific_extensions/neorv32/freertos_risc_v_chip_specific_extensions.h
  sw/example/demo_freeRTOS_xirq/demo/main_demo.c
  sw/example/demo_freeRTOS_xirq/main.c
  sw/example/demo_freeRTOS_xirq/makefile
Labels: SW

#717 Fix bug in neorv32_slink_available() function
  sw/lib/source/neorv32_slink.c
Labels: bug, SW

#718 [rtl] cleanups and code beautification
  CHANGELOG.md
  rtl/core/mem/neorv32_dmem.default.vhd
  rtl/core/mem/neorv32_dmem.legacy.vhd
  rtl/core/mem/neorv32_imem.default.vhd
  rtl/core/mem/neorv32_imem.legacy.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_regfile.vhd
  rtl/core/neorv32_fifo.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: HW, coding-style

#719 [sw] update crt0's early-boot trap handler
  CHANGELOG.md
  docs/datasheet/software.adoc
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  sw/common/crt0.S
  sw/example/processor_check/main.c
Labels: SW, optimization
