Repository stnolting/neorv32, pull requests merged in 2023-11, with the labels that each got.

#721 [rtl] upgrade neoTRNG to version 3
  CHANGELOG.md
  docs/datasheet/soc_trng.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_trng.vhd
  sw/example/demo_trng/main.c
Labels: HW, optimization

#722 Fix-up the litex wrapper
  rtl/system_integration/neorv32_litex_core_complex.vhd
Labels: bug, HW

#724 🧪 provide full hardware reset for all FFs
  CHANGELOG.md
  docs/datasheet/soc.adoc
  rtl/core/mem/neorv32_dmem.default.vhd
  rtl/core/mem/neorv32_dmem.legacy.vhd
  rtl/core/mem/neorv32_imem.default.vhd
  rtl/core/mem/neorv32_imem.legacy.vhd
  rtl/core/neorv32_boot_rom.vhd
  rtl/core/neorv32_cfs.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_cpu_cp_cfu.vhd
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_cpu_cp_shifter.vhd
  rtl/core/neorv32_crc.vhd
  rtl/core/neorv32_dcache.vhd
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_dmem.entity.vhd
  rtl/core/neorv32_fifo.vhd
  rtl/core/neorv32_gpio.vhd
  rtl/core/neorv32_gptmr.vhd
  rtl/core/neorv32_icache.vhd
  rtl/core/neorv32_imem.entity.vhd
  rtl/core/neorv32_mtime.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_onewire.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_pwm.vhd
  rtl/core/neorv32_sdi.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_uart.vhd
  rtl/core/neorv32_wdt.vhd
  rtl/core/neorv32_xip.vhd
  rtl/core/neorv32_xirq.vhd
Labels: HW, experimental, coding-style

#727 Fix comment mistake
  rtl/core/neorv32_cpu_cp_cfu.vhd
Labels: DOC

#730 [SPI] re-add high-speed mode
  CHANGELOG.md
  docs/datasheet/soc_spi.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_spi.vhd
  sw/lib/include/neorv32_spi.h
  sw/lib/source/neorv32_spi.c
Labels: enhancement, invalid

#731 [XIP] add clock divider for fine-tuning
  CHANGELOG.md
  docs/datasheet/soc_xip.adoc
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_xip.vhd
  sw/bootloader/bootloader.c
  sw/example/demo_xip/main.c
  sw/lib/include/neorv32_xip.h
  sw/lib/source/neorv32_xip.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#733 🐛 [FPU] fix wiring of exception flags
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_package.vhd
  sw/example/floating_point_test/main.c
Labels: bug, HW

#734 🐛 fix bug in instruction-misaligned exception handling
  CHANGELOG.md
  do.py
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/on_chip_debugger.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/processor_check/main.c
  sw/example/processor_check/run_check.sh
Labels: bug, risc-v compliance, HW

#735 [rtl] cleanup & rework/optimize CPU branch system
  CHANGELOG.md
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_regfile.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, optimization

#736 ✨ Add "ASIC style" register file option
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/soc.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_regfile.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_rte.c
Labels: enhancement, HW

#738 [rtl] Cleanup/update assertions and "auto-configuration"
  CHANGELOG.md
  rtl/core/mem/neorv32_imem.default.vhd
  rtl/core/mem/neorv32_imem.legacy.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_dcache.vhd
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_icache.vhd
  rtl/core/neorv32_intercon.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_wishbone.vhd
Labels: enhancement, HW

#739 Update hardware tigger module (Sdtrig) to version 1.0
  CHANGELOG.md
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/on_chip_debugger.adoc
  docs/references/riscv-debug-stable.pdf
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sim/neorv32_tb.vhd
  sw/example/demo_trigger_module/main.c
  sw/example/demo_trigger_module/makefile
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu_csr.h
Labels: bug, enhancement, risc-v compliance, HW
