Repository stnolting/neorv32, pull requests merged in 2024-10, with the labels that each got.

#1044 :warning: split B ISA extension into individual sub-extensions
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/soc.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_rte.c
Labels: HW, customization

#1046 :warning: rework CFU handshake interface
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_cfu.adoc
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_cp_cfu.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, optimization

#1047 ⚠️ remove `A` ISA extension, add `Zalrsc` ISA extension
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/soc.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/atomic_test/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_rte.c
Labels: risc-v compliance

#1048 Uprade neoTRNG to version 3.2
  CHANGELOG.md
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_trng.vhd
Labels: HW

#1049 :warning: rework PWM module
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_pwm.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_pwm.vhd
  rtl/core/neorv32_top.vhd
  rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd
  rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/demo_pwm/main.c
  sw/lib/include/neorv32_pwm.h
  sw/lib/source/neorv32_pwm.c
Labels: enhancement, HW

#1055 [ci] remove python doit
  .github/workflows/Documentation.yml
  .github/workflows/Processor.yml
  .gitignore
  do.py
Labels: CI

#1056 :warning: Remove OCD's DM legacy mode
  CHANGELOG.md
  docs/datasheet/on_chip_debugger.adoc
  docs/datasheet/soc.adoc
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
Labels: risc-v compliance, HW

#1058 [vivado ip] hide entire AXI-Stream interface in block diagram if disabled
  rtl/system_integration/neorv32_vivado_ip.tcl
Labels: enhancement, HW

#1062 Add link to https://linty-services.com
  README.md
Labels: DOC

#1063 [rtl/system_integration] create individual module for AXI4 Lite bridge
  CHANGELOG.md
  docs/datasheet/soc_xbus.adoc
  rtl/core/neorv32_package.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  rtl/system_integration/xbus2axi4lite_bridge.vhd
Labels: HW

#1066 Update dhry_1.c
  sw/example/dhrystone/dhry_1.c
Labels: SW

#1068 [rtl] minor RTL edits
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_decompressor.vhd
  rtl/core/neorv32_debug_dtm.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: HW, cleanup

#1072 🧪 Rework makefile/linker script memory configuration
  CHANGELOG.md
  docs/datasheet/software.adoc
  rtl/core/neorv32_package.vhd
  sim/neorv32_tb.vhd
  sw/common/neorv32.ld
  sw/example/atomic_test/makefile
  sw/example/bus_explorer/makefile
  sw/example/coremark/makefile
  sw/example/demo_blink_led/makefile
  sw/example/demo_blink_led_asm/makefile
  sw/example/demo_cfs/makefile
  sw/example/demo_cfu/makefile
  sw/example/demo_crc/makefile
  sw/example/demo_dma/makefile
  sw/example/demo_emulate_unaligned/makefile
  sw/example/demo_gptmr/makefile
  sw/example/demo_hpm/makefile
  sw/example/demo_mtime/makefile
  sw/example/demo_neopixel/makefile
  sw/example/demo_newlib/makefile
  sw/example/demo_onewire/makefile
  sw/example/demo_pwm/makefile
  sw/example/demo_sdi/makefile
  sw/example/demo_slink/makefile
  sw/example/demo_spi/makefile
  sw/example/demo_spi_irq/makefile
  sw/example/demo_trng/makefile
  sw/example/demo_twi/makefile
  sw/example/demo_wdt/makefile
  sw/example/demo_xip/makefile
  sw/example/demo_xirq/makefile
  sw/example/dhrystone/makefile
  sw/example/float_corner_test/makefile
  sw/example/floating_point_test/makefile
  sw/example/game_of_life/makefile
  sw/example/hello_cpp/makefile
  sw/example/hello_world/makefile
  sw/example/makefile
  sw/example/performance_tests/I/makefile
  sw/example/performance_tests/M/makefile
  sw/example/performance_tests/Zfinx/makefile
  sw/example/processor_check/makefile
Labels: SW, experimental

#1077 [sw/common] Cleanup central makefile and linker script
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/rationale.adoc
  docs/datasheet/software.adoc
  rtl/core/neorv32_package.vhd
  sw/bootloader/makefile
  sw/common/common.mk
  sw/common/neorv32.ld
  sw/example/eclipse/makefile
  sw/openocd/openocd_neorv32.cfg
Labels: SW, experimental, cleanup
