Repository stnolting/neorv32, pull requests merged in 2024-08, with the labels that each got.

#971 ⚠️ rework CFU (remove R5-type instructions)
  CHANGELOG.md
  docs/datasheet/cpu_cfu.adoc
  docs/figures/cfu_r5type_instruction_a.png
  docs/figures/cfu_r5type_instruction_b.png
  docs/sources/cfu_r5type_instructionA.json
  docs/sources/cfu_r5type_instructionB.json
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_cfu.vhd
  rtl/core/neorv32_cpu_regfile.vhd
  rtl/core/neorv32_package.vhd
  sw/example/demo_cfu/main.c
  sw/lib/include/neorv32_cpu_cfu.h
Labels: HW

#972 Rework (and auto-generate) file-list files
  docs/datasheet/overview.adoc
  docs/datasheet/software.adoc
  rtl/README.md
  rtl/cpu_hdl_files.f
  rtl/file_list_cpu.f
  rtl/file_list_soc.f
  rtl/generate_file_lists.sh
  rtl/processor_hdl_files.f
  sw/common/common.mk
Labels: enhancement, HW

#975 [docs] fix spelling
  docs/userguide/application_specific_configuration.adoc
Labels: DOC

#976 [vivado_ip] fix error when AXI port is unconnected
  CHANGELOG.md
  docs/userguide/packaging_vivado.adoc
  rtl/core/neorv32_package.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
Labels: bug, HW

#978 [vivado_ip] fix unconnected variable-size inputs
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
Labels: bug

#980 [vivado_ip] constrain minimal size of variable-sized output ports
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
Labels: HW

#984 Minor RTL edits
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_package.vhd
Labels: HW

#985 :warning: reorganize core RTL files :warning:
  CHANGELOG.md
  README.md
  docs/datasheet/overview.adoc
  docs/datasheet/soc_dmem.adoc
  docs/datasheet/soc_imem.adoc
  docs/userguide/general_hw_setup.adoc
  rtl/README.md
  rtl/core/mem/README.md
  rtl/core/mem/neorv32_dmem.default.vhd
  rtl/core/mem/neorv32_dmem.legacy.vhd
  rtl/core/mem/neorv32_imem.default.vhd
  rtl/core/mem/neorv32_imem.legacy.vhd
  rtl/core/neorv32_dmem.entity.vhd
  rtl/core/neorv32_dmem.vhd
  rtl/core/neorv32_imem.entity.vhd
  rtl/core/neorv32_imem.vhd
  rtl/core/neorv32_package.vhd
  rtl/file_list_soc.f
  rtl/generate_file_lists.sh
  rtl/system_integration/neorv32_vivado_ip.tcl
  sim/run.py
Labels: HW, coding-style, cleanup

#990 [rtl] minor timing and area optimizations
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_cond.vhd
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_cpu_cp_shifter.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_cpu_regfile.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_trng.vhd
Labels: HW, optimization

#996 RTL reworks, cleanups and optimizations
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_crc.vhd
  rtl/core/neorv32_imem.vhd
  rtl/core/neorv32_package.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu_csr.h
Labels: HW, optimization, cleanup

#998 :bug: fix minor regression bug; minor RTL optimizations
  CHANGELOG.md
  docs/datasheet/soc.adoc
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_intercon.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: HW, optimization
