Repository stnolting/neorv32, pull requests merged in 2024-12, with the labels that each got.

#1107 [sw] Use build folder and add example for more complex project structure
  .gitignore
  docs/datasheet/software.adoc
  docs/userguide/application_program_compilation.adoc
  sw/common/common.mk
  sw/example/coremark/include/core_portme.h
  sw/example/coremark/include/coremark.h
  sw/example/coremark/makefile
  sw/example/coremark/source/core_list_join.c
  sw/example/coremark/source/core_main.c
  sw/example/coremark/source/core_matrix.c
  sw/example/coremark/source/core_portme.c
  sw/example/coremark/source/core_state.c
  sw/example/coremark/source/core_util.c
  sw/example/coremark/source/cvt.c
  sw/example/coremark/source/ee_printf.c
Labels: enhancement, SW, cleanup

#1113 ✨ add ONEWIRE command FIFO; 🐛 fix ONEWIRE status flag
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_onewire.adoc
  rtl/core/neorv32_onewire.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sim/neorv32_tb.vhd
  sw/example/demo_onewire/main.c
  sw/example/demo_onewire/onewire_aux.h
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_onewire.h
  sw/lib/source/neorv32_onewire.c
  sw/svd/neorv32.svd
Labels: bug, enhancement, HW

#1096 use vhdl 2008 standard in ghdl simulations
  sim/ghdl.run.sh
Labels: CI

#1118 🧪 Shrink bootloader ISA and RAM requirements
  CHANGELOG.md
  docs/datasheet/software_bootloader.adoc
  docs/userguide/customizing_the_bootloader.adoc
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  sw/bootloader/bootloader.c
  sw/bootloader/makefile
Labels: enhancement, experimental

#1119 [sim] rework default testbench
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
  sim/neorv32_tb.vhd
  sim/sim_uart_rx.vhd
  sim/xbus_gateway.vhd
  sim/xbus_memory.vhd
Labels: enhancement, HW

#1120 ⚠️ rework TRNG
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_trng.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_fifo.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_xbus.vhd
  sw/example/demo_trng/main.c
  sw/example/game_of_life/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_trng.h
  sw/lib/source/neorv32_trng.c
  sw/svd/neorv32.svd
Labels: HW, cleanup

#1121 ✨ add new module: device-mode I²C controller ("TWD")
  CHANGELOG.md
  README.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/soc_twd.adoc
  docs/datasheet/soc_twi.adoc
  docs/figures/neorv32_processor.png
  docs/figures/twd_sequences.png
  docs/sources/twd_sequences.json
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_twd.vhd
  rtl/file_list_soc.f
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/include/neorv32_twd.h
  sw/lib/source/neorv32_rte.c
  sw/lib/source/neorv32_twd.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#1122 Docs: removed Chapter about VHDL Development Environment
  docs/userguide/content.adoc
  docs/userguide/vhdl_development_environment.adoc
Labels: DOC

#1105 🧪 [pmp] use time-multiplex approach
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, experimental, optimization

#1123 minor rtl cleanups and optimization
  CHANGELOG.md
  docs/datasheet/overview.adoc
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_crypto.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_xirq.vhd
  sim/ghdl.run.sh
  sim/ghdl.sh
Labels: HW, cleanup

#1124 Relocate clock gating switch
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_sysinfo.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/file_list_cpu.f
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_rte.c
  sw/svd/neorv32.svd
Labels: HW, cleanup

#1125 ⚠️ Rename CPU tuning options / generics
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/soc.adoc
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
Labels: HW, cleanup

#1126 ⚠️ Rework IO/peripheral address space
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_bootrom.adoc
  docs/datasheet/soc_cfs.adoc
  docs/datasheet/soc_crc.adoc
  docs/datasheet/soc_dma.adoc
  docs/datasheet/soc_gpio.adoc
  docs/datasheet/soc_gptmr.adoc
  docs/datasheet/soc_mtime.adoc
  docs/datasheet/soc_neoled.adoc
  docs/datasheet/soc_onewire.adoc
  docs/datasheet/soc_pwm.adoc
  docs/datasheet/soc_sdi.adoc
  docs/datasheet/soc_slink.adoc
  docs/datasheet/soc_spi.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/soc_trng.adoc
  docs/datasheet/soc_twd.adoc
  docs/datasheet/soc_twi.adoc
  docs/datasheet/soc_uart.adoc
  docs/datasheet/soc_wdt.adoc
  docs/datasheet/soc_xip.adoc
  docs/datasheet/soc_xirq.adoc
  docs/figures/address_space.png
  docs/figures/neorv32_bus.png
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_boot_rom.vhd
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_imem.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/file_list_soc.f
  sw/bootloader/bootloader.c
  sw/bootloader/makefile
  sw/image_gen/image_gen.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_cfs.h
  sw/svd/neorv32.svd
Labels: enhancement, HW

#1130 ⚠️ Replace MTIME by CLINT
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_clint.adoc
  docs/datasheet/soc_mtime.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/software.adoc
  docs/datasheet/software_bootloader.adoc
  docs/datasheet/software_rte.adoc
  docs/figures/neorv32_bus.png
  docs/figures/neorv32_processor.png
  docs/userguide/simulating_the_processor.adoc
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_clint.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_mtime.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/file_list_soc.f
  rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd
  rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  rtl/test_setups/README.md
  rtl/test_setups/neorv32_test_setup_approm.vhd
  rtl/test_setups/neorv32_test_setup_bootloader.vhd
  rtl/test_setups/neorv32_test_setup_on_chip_debugger.vhd
  sim/neorv32_tb.vhd
  sw/bootloader/bootloader.c
  sw/example/demo_clint/Makefile
  sw/example/demo_clint/main.c
  sw/example/dhrystone/README.md
  sw/example/dhrystone/dhry_1.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_clint.h
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_clint.c
  sw/lib/source/neorv32_cpu.c
  sw/lib/source/neorv32_newlib.c
  sw/lib/source/neorv32_rte.c
  sw/svd/neorv32.svd
Labels: risc-v compliance, HW

#1131 Add "out-of-band" signals to internal bus interface
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/figures/bus_interface.png
  docs/figures/bus_interface_atomic.png
  docs/sources/bus_interface.json
  docs/sources/bus_interface_atomic.json
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_wdt.vhd
Labels: HW, cleanup

#1128 Update neorv32_cpu_control.vhd
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, HW

#1132 🧪 add multi-hart support to on-chip-debugger's debu module
  CHANGELOG.md
  docs/datasheet/on_chip_debugger.adoc
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/ocd-firmware/debug_rom.ld
  sw/ocd-firmware/park_loop.S
Labels: enhancement, HW, experimental

#1136 [clint] automate MTIMECMP selection
  rtl/core/neorv32_bootloader_image.vhd
  sw/bootloader/bootloader.c
  sw/example/demo_clint/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_clint.h
  sw/lib/source/neorv32_clint.c
  sw/openocd/openocd_neorv32.cfg
Labels: SW, cleanup

#1137 ⚠️ Move RTE information functions to AUX library
  sw/example/hello_cpp/main.cpp
  sw/example/hello_world/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_aux.h
  sw/lib/include/neorv32_rte.h
  sw/lib/source/neorv32_aux.c
  sw/lib/source/neorv32_rte.c
Labels: SW, cleanup
