Repository stnolting/neorv32, pull requests merged in 2024-03, with the labels that each got.

#842 [rtl] add generic cache module (not used yet)
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_package.vhd
  sim/neorv32_tb.vhd
  sw/common/common.mk
  sw/example/processor_check/main.c
Labels: HW, optimization

#843 rtl cleanups and optimizations
  CHANGELOG.md
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_dcache.vhd
  rtl/core/neorv32_package.vhd
  sw/example/coremark/core_portme.c
  sw/example/processor_check/main.c
Labels: HW, optimization, coding-style

#845 ⚠️ remove Wishbone tag signal
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_wishbone.adoc
  docs/figures/wishbone_classic_read.png
  docs/figures/wishbone_pipelined_write.png
  docs/sources/wishbone_classic_read.json
  docs/sources/wishbone_pipelined_write.json
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_wishbone.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
Labels: HW

#846 ⚠️⚠️ Rename external bus interface
  CHANGELOG.md
  README.md
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/soc_wishbone.adoc
  docs/datasheet/soc_xbus.adoc
  docs/figures/neorv32_processor.png
  docs/figures/wishbone_classic_read.png
  docs/figures/wishbone_pipelined_write.png
  docs/sources/wishbone_classic_read.json
  docs/sources/wishbone_pipelined_write.json
  docs/userguide/adding_custom_hw_modules.adoc
  docs/userguide/application_specific_configuration.adoc
  docs/userguide/litex_support.adoc
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_xbus.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_rte.c
  sw/svd/neorv32.svd
Labels: HW

#849 ✨ Add optional external bus interface cache (XCACHE)
  CHANGELOG.md
  README.md
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_xbus.adoc
  docs/figures/neorv32_bus.png
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_rte.c
  sw/svd/neorv32.svd
Labels: HW

#850 :warning: processor configuration edits / clean-ups
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/on_chip_debugger.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_dma.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/soc_xbus.adoc
  docs/datasheet/software.adoc
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_xbus.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/common/neorv32.ld
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_cpu.c
  sw/lib/source/neorv32_rte.c
  sw/svd/neorv32.svd
Labels: risc-v compliance, HW, SW, cleanup

#851 Minor cache updates
  CHANGELOG.md
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_icache.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: enhancement, HW

#852 [litex] update core complex wrapper
  rtl/system_integration/neorv32_litex_core_complex.vhd
Labels: HW

#853 rework cache system
  CHANGELOG.md
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_dcache.adoc
  docs/datasheet/soc_icache.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/soc_xbus.adoc
  docs/datasheet/soc_xip.adoc
  docs/figures/neorv32_bus.png
  rtl/core/neorv32_dcache.vhd
  rtl/core/neorv32_icache.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_xip.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/demo_xip/main.c
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_rte.c
  sw/svd/neorv32.svd
Labels: HW

#854 Connected SPI bus to on-board Flash and SPI peripheral
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
Labels: bug, HW

#855 Update CFU example: use XTEA as "real world" demo application
  CHANGELOG.md
  docs/datasheet/cpu_cfu.adoc
  rtl/core/neorv32_cpu_cp_cfu.vhd
  rtl/core/neorv32_package.vhd
  sw/example/demo_cfu/main.c
Labels: enhancement, HW, SW

#844 Updated Performance test
  sim/simple/ghdl.run.sh
  sim/simple/ghdl.sh
  sim/simple/neorv32_tb.simple.vhd
  sw/common/common.mk
  sw/example/performance_tests/I/README.md
  sw/example/performance_tests/I/main.c
  sw/example/performance_tests/I/makefile
  sw/example/performance_tests/M/README.md
  sw/example/performance_tests/M/main.c
  sw/example/performance_tests/M/makefile
  sw/example/performance_tests/Zfinx/README.md
  sw/example/performance_tests/Zfinx/main.c
  sw/example/performance_tests/Zfinx/makefile
  sw/example/performance_tests/makefile
  sw/example/performance_tests/run_performance.sh
  sw/example/processor_check/makefile
Labels: DOC, enhancement, SW

#857 CPU RTL optimization
  CHANGELOG.md
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_cpu_regfile.vhd
  rtl/core/neorv32_intercon.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: HW, optimization

#858 :warning: remove WDT + TRNG interrupts; :bug: fix bug in core-complex clocking during sleep
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_trng.adoc
  docs/datasheet/soc_wdt.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_wdt.vhd
  sim/neorv32_tb.vhd
  sw/example/demo_trng/main.c
  sw/example/demo_wdt/main.c
  sw/example/game_of_life/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_trng.h
  sw/lib/source/neorv32_trng.c
  sw/svd/neorv32.svd
Labels: bug, HW, cleanup

#859 :warning: rework ONEWIRE and GPTMR interrupts
  CHANGELOG.md
  docs/datasheet/soc_onewire.adoc
  rtl/core/neorv32_cfs.vhd
  rtl/core/neorv32_gptmr.vhd
  rtl/core/neorv32_onewire.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sdi.vhd
Labels: HW, cleanup

#860 :warning: rework TWI interrupt
  CHANGELOG.md
  docs/datasheet/soc_dma.adoc
  docs/datasheet/soc_twi.adoc
  docs/datasheet/soc_xirq.adoc
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_xirq.vhd
  sw/lib/source/neorv32_xirq.c
Labels: HW, cleanup

#864 :bug: fix DMA fence flag, :warning: rework CPU FIRQs
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/soc.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_package.vhd
  sim/neorv32_tb.vhd
  sw/example/demo_dma/main.c
  sw/example/demo_gptmr/main.c
  sw/example/demo_slink/main.c
  sw/example/demo_spi_irq/drv/neorv32_spi_irq.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu.h
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_cpu.c
  sw/lib/source/neorv32_rte.c
  sw/lib/source/neorv32_xirq.c
Labels: bug, risc-v compliance, HW, cleanup

#862 Support tool-specific standard flags in makefile
  docs/datasheet/software.adoc
  sw/common/common.mk
Labels: enhancement, SW

#865 :warning: rework TWI module
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_twi.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_twi.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/demo_twi/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_twi.h
  sw/lib/source/neorv32_twi.c
  sw/svd/neorv32.svd
Labels: enhancement, HW, SW
