Repository stnolting/neorv32, pull requests merged in 2024-09, with the labels that each got.

#1004 minor RTL cleanups and optimizations
  CHANGELOG.md
  rtl/core/neorv32_cfs.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sw/example/demo_cfs/main.c
Labels: HW, optimization, cleanup

#1005 🧪 Remove "loop" from memory initialization function
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
Labels: HW, experimental

#1007 [sw] fix `sysinfo` doxygen header
  sw/lib/include/neorv32_sysinfo.h
Labels: DOC

#1008 optimize CSR address logic
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_fifo.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, optimization

#1010 Minor rtl/CSR optimizations
  CHANGELOG.md
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/on_chip_debugger.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_intercon.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: HW, optimization

#1009 Cleanup debug symbols
  docs/datasheet/software.adoc
  docs/userguide/eclipse_ide.adoc
  sw/common/common.mk
  sw/example/eclipse/.settings/org.eclipse.cdt.core.prefs
  sw/example/eclipse/.settings/org.eclipse.embedcdt.debug.gdbjtag.openocd.core.prefs
  sw/example/eclipse/.settings/org.eclipse.embedcdt.managedbuild.cross.riscv.core.prefs
  sw/example/eclipse/makefile
Labels: SW

#1014 minor HDL cleanups and otimizations
  CHANGELOG.md
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_intrinsics.h
Labels: HW, optimization, cleanup

#1015 Cleanup and extend watch dog's reset-cause logic
  CHANGELOG.md
  docs/datasheet/soc_wdt.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_wdt.vhd
  sw/example/demo_wdt/main.c
  sw/lib/include/neorv32_wdt.h
  sw/lib/source/neorv32_wdt.c
Labels: enhancement, HW

#1017 ⚠️ Refactor RTL files / hierarchy
  CHANGELOG.md
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sys.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_wdt.vhd
  rtl/core/neorv32_xip.vhd
  rtl/file_list_soc.f
Labels: HW, coding-style, cleanup

#1018 :bug: fix B.CTZ decoding regression bug
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, HW

#1019 Massive rtl code cleanup
  CHANGELOG.md
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_clockgate.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_cond.vhd
  rtl/core/neorv32_cpu_decompressor.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_gpio.vhd
  rtl/core/neorv32_mtime.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_onewire.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_uart.vhd
Labels: HW, coding-style, cleanup

#1021 :bug: fix stack alignment upon first procedure entry
  CHANGELOG.md
  docs/datasheet/software.adoc
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  sw/common/crt0.S
  sw/common/neorv32.ld
  sw/lib/include/neorv32.h
Labels: bug, SW, experimental

#1026 [rtl] signal renamings and cleanups to make the code more readable
  CHANGELOG.md
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_xirq.vhd
Labels: HW, cleanup

#1028 :bug: fix minor bug in FPU MUL instruction
  CHANGELOG.md
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, HW

#1030 [rtl] remove redundant `prog_buf`
  rtl/core/neorv32_debug_dm.vhd
Labels: HW, cleanup

#1032 [cpu] rework ALU instruction decoding and CPU co-processor interface
  CHANGELOG.md
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_cpu_cp_cond.vhd
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_cpu_cp_shifter.vhd
  rtl/core/neorv32_package.vhd
  sw/example/processor_check/main.c
Labels: HW, optimization

#1033 ✨ [cpu] add support for RISC-V scalar cryptography ISA extensions
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_crypto.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/file_list_cpu.f
  rtl/file_list_soc.f
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/processor_check/makefile
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_rte.c
Labels: enhancement, HW

#1035 Fix typo trap table
  docs/datasheet/cpu.adoc
Labels: DOC

#1036 Add Zknt ISA extension
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_rte.c
Labels: risc-v compliance, HW

#1037 :sparkles: add support for RISC-V `Zbkb` ISA extension
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/soc.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_cpu_cp_crypto.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/processor_check/makefile
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_rte.c
Labels: enhancement, risc-v compliance, HW

#1038 ✨ add support for RISC-V `Zbkc` ISA extension
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/on_chip_debugger.adoc
  docs/datasheet/soc.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/processor_check/makefile
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_rte.c
Labels: enhancement, risc-v compliance, HW

#1039 Add `Zkn` ISA extension
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_rte.c
Labels: enhancement, risc-v compliance, HW

#1040 ✨ add support for RISC-V `Zks*` ISA extensions
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/soc.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_crypto.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/processor_check/makefile
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_rte.c
Labels: enhancement, risc-v compliance, HW

#1041 ⚠️ Rename CPU ISA configuration generics
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/rationale.adoc
  docs/datasheet/soc.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_crypto.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  rtl/test_setups/neorv32_test_setup_approm.vhd
  rtl/test_setups/neorv32_test_setup_bootloader.vhd
  rtl/test_setups/neorv32_test_setup_on_chip_debugger.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
Labels: cleanup
