Repository stnolting/neorv32, pull requests merged in 2024-11, with the labels that each got.

#1083 ⚠️ Relocate VUnit testbench to another sub-repository (neorv32-vunit)
  .github/workflows/Processor.yml
  README.md
  docs/datasheet/overview.adoc
  docs/userguide/simulating_the_processor.adoc
  sim/README.md
  sim/ghdl.run.sh
  sim/ghdl.setup.sh
  sim/ghdl.sh
  sim/neorv32_tb.vhd
  sim/run.py
  sim/simple/ghdl.sh
  sim/simple/neorv32_tb.simple.vhd
  sim/simple/uart_rx.simple.vhd
  sim/uart_rx.vhd
  sim/uart_rx_pkg.vhd
  sw/common/common.mk
  sw/example/hello_world/makefile
  sw/example/processor_check/makefile
Labels: CI, cleanup

#1085 [github workflow] remove packages
  .github/workflows/Processor.yml
Labels: CI, cleanup

#1086 ⚠️ Rework processor boot configuration
  CHANGELOG.md
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_bootrom.adoc
  docs/datasheet/soc_dmem.adoc
  docs/datasheet/soc_imem.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/software_bootloader.adoc
  docs/figures/neorv32_boot_configurations.png
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_dmem.vhd
  rtl/core/neorv32_imem.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd
  rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  rtl/test_setups/neorv32_test_setup_approm.vhd
  rtl/test_setups/neorv32_test_setup_bootloader.vhd
  rtl/test_setups/neorv32_test_setup_on_chip_debugger.vhd
  sim/neorv32_tb.vhd
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_rte.c
  sw/svd/neorv32.svd
Labels: HW

#1090 Minor rtl edits and cleanups
  CHANGELOG.md
  rtl/core/neorv32_cfs.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_uart.vhd
  rtl/system_integration/neorv32_vivado_ip.vhd
  rtl/system_integration/xbus2axi4lite_bridge.vhd
Labels: HW, cleanup

#1093 Rework default testbench
  CHANGELOG.md
  docs/datasheet/soc_uart.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sim/ghdl.run.sh
  sim/ghdl.setup.sh
  sim/ghdl.sh
  sim/neorv32_tb.vhd
  sim/sim_uart_rx.vhd
  sim/uart_rx.vhd
  sim/xbus_gateway.vhd
  sim/xbus_memory.vhd
  sw/example/hello_world/makefile
  sw/example/processor_check/main.c
  sw/example/processor_check/makefile
Labels: optimization, cleanup

#1091 🧪 Use xpack risc-v gcc as default prebuilt toolchain
  .github/workflows/Processor.yml
  CHANGELOG.md
  docs/datasheet/software.adoc
  docs/userguide/sw_toolchain_setup.adoc
  rtl/core/neorv32_package.vhd
  sw/common/common.mk
  sw/example/dhrystone/README.md
  sw/example/float_corner_test/neorv32_zfinx_extension_intrinsics.h
  sw/example/makefile
Labels: SW, CI, experimental

#1099 [CPU control] large code cleanup
  CHANGELOG.md
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, coding-style, cleanup

#1102 Fixed typo and cpu_alu architecture renaming for consistency
  rtl/core/neorv32_cpu_alu.vhd
  sw/example/bus_explorer/main.c
Labels: DOC, cleanup

#1101 [docs/makefile] Copy figures also for single targets
  docs/Makefile
Labels: DOC
