Repository stnolting/neorv32, pull requests merged in 2024-05, with the labels that each got.

#889 minor rtl cleanups
  CHANGELOG.md
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_package.vhd
  sw/common/common.mk
  sw/example/coremark/core_portme.c
Labels: HW, coding-style, cleanup

#891 Fix UART receiver
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_uart.vhd
Labels: bug, HW

#894 Add NEORV32 as Vivado IP
  CHANGELOG.md
  docs/figures/neorv32_axi_soc.png
  docs/figures/vivado_ip_gui.png
  docs/figures/vivado_ip_soc.png
  docs/userguide/content.adoc
  docs/userguide/packaging_vivado.adoc
  rtl/core/neorv32_package.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
Labels: enhancement, experimental

#900 Cleanup SW library
  docs/datasheet/software.adoc
  sw/lib/include/legacy.h
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_cfs.h
  sw/lib/include/neorv32_cpu.h
  sw/lib/include/neorv32_cpu_amo.h
  sw/lib/include/neorv32_cpu_cfu.h
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/include/neorv32_crc.h
  sw/lib/include/neorv32_dm.h
  sw/lib/include/neorv32_dma.h
  sw/lib/include/neorv32_gpio.h
  sw/lib/include/neorv32_gptmr.h
  sw/lib/include/neorv32_intrinsics.h
  sw/lib/include/neorv32_mtime.h
  sw/lib/include/neorv32_neoled.h
  sw/lib/include/neorv32_onewire.h
  sw/lib/include/neorv32_pwm.h
  sw/lib/include/neorv32_rte.h
  sw/lib/include/neorv32_sdi.h
  sw/lib/include/neorv32_slink.h
  sw/lib/include/neorv32_spi.h
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/include/neorv32_trng.h
  sw/lib/include/neorv32_twi.h
  sw/lib/include/neorv32_uart.h
  sw/lib/include/neorv32_wdt.h
  sw/lib/include/neorv32_xip.h
  sw/lib/include/neorv32_xirq.h
  sw/lib/source/neorv32_cfs.c
  sw/lib/source/neorv32_cpu.c
  sw/lib/source/neorv32_cpu_amo.c
  sw/lib/source/neorv32_cpu_cfu.c
  sw/lib/source/neorv32_crc.c
  sw/lib/source/neorv32_dma.c
  sw/lib/source/neorv32_gpio.c
  sw/lib/source/neorv32_gptmr.c
  sw/lib/source/neorv32_mtime.c
  sw/lib/source/neorv32_neoled.c
  sw/lib/source/neorv32_onewire.c
  sw/lib/source/neorv32_pwm.c
  sw/lib/source/neorv32_rte.c
  sw/lib/source/neorv32_sdi.c
  sw/lib/source/neorv32_slink.c
  sw/lib/source/neorv32_spi.c
  sw/lib/source/neorv32_trng.c
  sw/lib/source/neorv32_twi.c
  sw/lib/source/neorv32_uart.c
  sw/lib/source/neorv32_wdt.c
  sw/lib/source/neorv32_xip.c
  sw/lib/source/neorv32_xirq.c
  sw/lib/source/syscalls.c
Labels: SW, cleanup

#901 Add back Dhrystone port
  sw/example/dhrystone/LICENSE
  sw/example/dhrystone/README.md
  sw/example/dhrystone/dhry.h
  sw/example/dhrystone/dhry_1.c
  sw/example/dhrystone/dhry_2.c
  sw/example/dhrystone/makefile
Labels: SW

#903 Update neorv32_sdi.vhd - Minor typo correction
  rtl/core/neorv32_sdi.vhd
Labels: HW, coding-style, cleanup

#904 Add COE and MEM file generator options
  .gitignore
  docs/datasheet/software.adoc
  sw/common/common.mk
  sw/image_gen/image_gen.c
Labels: enhancement, experimental

#905 [FPU] prevent GCC from emitting fused multiply-add instructions
  docs/datasheet/cpu.adoc
  docs/datasheet/software.adoc
  sw/common/common.mk
  sw/lib/source/neorv32_uart.c
Labels: SW, experimental

#908 Add SLINK routing information ports
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_slink.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_slink.h
  sw/lib/source/neorv32_slink.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#911 Make XIRQ trigger configuration *programmable*
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_xirq.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_xirq.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/demo_xirq/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_xirq.h
  sw/lib/source/neorv32_xirq.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#909 Add HDL file list files
  docs/datasheet/overview.adoc
  rtl/core/cpu_hdl_files.f
  rtl/core/processor_hdl_files.f
Labels: HW, experimental

#913 Add variable-sized ports to Vivado IP block
  CHANGELOG.md
  docs/figures/vivado_ip_soc.png
  docs/userguide/packaging_vivado.adoc
  rtl/core/neorv32_package.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
Labels: enhancement, HW

#915 Fix uncached/cached access priority
  CHANGELOG.md
  docs/datasheet/soc_dcache.adoc
  docs/datasheet/soc_icache.adoc
  docs/datasheet/soc_xbus.adoc
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_intercon.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu.h
Labels: bug, HW
