Repository stnolting/neorv32, pull requests merged in 2024-01, with the labels that each got.

#759 Add GPTMR timer capture
  CHANGELOG.md
  README.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_gptmr.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_gptmr.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/demo_dma/main.c
  sw/example/demo_gptmr/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_gptmr.h
  sw/lib/source/neorv32_gptmr.c
  sw/svd/neorv32.svd
Labels: bug, enhancement, HW

#760 [rtl] minor code cleanups
  CHANGELOG.md
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_shifter.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_debug_dtm.vhd
  rtl/core/neorv32_package.vhd
Labels: HW

#762 [rtl/core] add again mtime_o to top entity
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_mtime.adoc
  rtl/core/neorv32_mtime.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
Labels: enhancement, HW

#763 [rtl] fix minor VHDL coding style issue
  CHANGELOG.md
  rtl/core/neorv32_cpu_cp_shifter.vhd
  rtl/core/neorv32_package.vhd
Labels: coding-style

#764 [rtl] minor cleanups and optimizations
  CHANGELOG.md
  rtl/core/neorv32_cfs.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_cfu.vhd
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_cpu_cp_shifter.vhd
  rtl/core/neorv32_fifo.vhd
  rtl/core/neorv32_intercon.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/example/demo_cfu/main.c
Labels: HW, optimization, coding-style

#769 [rtl] optimize bus switch
  CHANGELOG.md
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_intercon.vhd
  rtl/core/neorv32_package.vhd
  sw/bootloader/bootloader.c
  sw/common/crt0.S
Labels: HW, optimization

#771 :bug: Remove RVC float load/store instructions
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_decompressor.vhd
  rtl/core/neorv32_package.vhd
  sw/example/processor_check/main.c
Labels: bug, risc-v compliance, HW

#775 ✨ add optional CPU clock gating
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_sysinfo.adoc
  rtl/core/neorv32_clockgate.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_rte.c
  sw/svd/neorv32.svd
Labels: enhancement, HW, experimental

#776 :bug: fix typo that renders the clock gating useless
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, HW

#777 [rtl] improve CPU front end
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, optimization

#778 Updated FIFO NULL assertion fix
  CHANGELOG.md
  rtl/core/neorv32_fifo.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, optimization, coding-style

#779 set top entiy input defaults to 'L' or 'H'
  CHANGELOG.md
  docs/datasheet/soc.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: HW

#780 🧪 extend switchable clock domain
  CHANGELOG.md
  docs/datasheet/soc.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: enhancement, HW, experimental

#783 Fix for issue #782
  CHANGELOG.md
  rtl/core/neorv32_cpu_decompressor.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, risc-v compliance, HW
