Repository stnolting/neorv32, pull requests merged in 2024-02, with the labels that each got.

#786 Add support for page fault exceptions
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/include/neorv32_rte.h
  sw/lib/source/neorv32_rte.c
Labels: enhancement, HW, experimental

#790 [cpu] fix minor bug in instruction request bus
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, HW

#788 Fix for issue #785: FPU fflags no being asserted correctly
  rtl/core/neorv32_cpu_cp_fpu.vhd
Labels: bug, risc-v compliance, HW

#792 🐛 [cpu] fix non-stable privilege signal of instruction interface
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, HW

#797 [CPU] close further illegal instruction loopholes
  CHANGELOG.md
  rtl/core/neorv32_cpu_decompressor.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, risc-v compliance

#799 ✨ add optional XIP cache
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/soc_xip.adoc
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_xip.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/bootloader/bootloader.c
  sw/example/demo_xip/main.c
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/include/neorv32_xip.h
  sw/lib/source/neorv32_rte.c
  sw/lib/source/neorv32_xip.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#800 add fence signal to CPU bus
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_dcache.adoc
  docs/datasheet/soc_icache.adoc
  docs/datasheet/soc_xip.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_dcache.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_icache.vhd
  rtl/core/neorv32_intercon.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_xip.vhd
  rtl/system_integration/neorv32_SystemTop_AvalonMM.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
Labels: HW

#802 :bug: fix fence signal pass-through in caches
  CHANGELOG.md
  rtl/core/neorv32_dcache.vhd
  rtl/core/neorv32_icache.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_xip.vhd
Labels: bug, HW

#804 minor rtl edits
  CHANGELOG.md
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_package.vhd
  sw/bootloader/bootloader.c
Labels: HW, optimization

#794 Fixes to the FPU for issue #791
  CHANGELOG.md
  rtl/core/neorv32_cpu_cp_fpu.vhd
  rtl/core/neorv32_package.vhd
  sw/example/floating_point_test/neorv32_zfinx_extension_intrinsics.h
Labels: bug, risc-v compliance, HW

#806 :bug: fix another C-ISA loophole
  CHANGELOG.md
  rtl/core/neorv32_cpu_decompressor.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, risc-v compliance, HW

#807 Add DMA fence operation
  CHANGELOG.md
  docs/datasheet/soc_dma.adoc
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_package.vhd
  sw/example/demo_dma/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_dma.h
  sw/lib/source/neorv32_dma.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#808 Allow disabling certain PMP modes
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/soc.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
Labels: enhancement, HW

#809 [revert] remove page faults support
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/include/neorv32_rte.h
  sw/lib/source/neorv32_rte.c
Labels: HW

#812 :bug: Fix bug in CRT0 trap handler
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bootloader_image.vhd
  sw/common/crt0.S
  sw/common/neorv32.ld
Labels: bug, SW

#811 :warning: Rework hardware performance monitor (HPM) events
  CHANGELOG.md
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sw/example/coremark/core_portme.c
  sw/example/coremark/core_portme.h
  sw/example/demo_hpm/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu_csr.h
Labels: HW

#813 🧪 [makefile] pass CC_OPTS variable as define string
  docs/datasheet/software.adoc
  sw/common/common.mk
  sw/example/coremark/core_portme.h
Labels: SW, experimental

#814 ⚠️ remove Smcntrpmf ISA extension
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sim/neorv32_tb.vhd
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_rte.c
Labels: HW

#817 [sim] add simulation check to sw makefiles as target 'sim-check'
  .github/workflows/Processor.yml
  sim/simple/ghdl.run.sh
  sw/example/hello_world/makefile
  sw/example/processor_check/makefile
  sw/example/processor_check/run_check.sh
Labels: enhancement, CI

#815 [SLINK] add AXI-stream-compatible "tlast" signals
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_slink.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
  sim/neorv32_tb.vhd
  sim/simple/neorv32_tb.simple.vhd
  sw/example/demo_slink/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_slink.h
  sw/lib/source/neorv32_slink.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#819 [docs/userguide/simulating_the_processor] add admonition and recommend MARCH=rv32im to build hello_world
  docs/userguide/simulating_the_processor.adoc
Labels: DOC

#821 🐛 Fix write access to mip.firq CSR bits
  CHANGELOG.md
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sw/lib/include/neorv32_cpu_csr.h
Labels: bug, HW

#822 [ci] test example hello_world as well
  .github/workflows/Processor.yml
Labels: CI

#827 [fifo] fix (Vivado) synthesis issue
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_fifo.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sdi.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_uart.vhd
Labels: HW, optimization

#831 Added dummy clocks for SLINK streams in AXI4-Lite wrapper
  docs/userguide/packaging_vivado.adoc
  rtl/system_integration/neorv32_SystemTop_axi4lite.vhd
Labels: HW, optimization

#829 :bug: fix atomic write/clear/set accesses of clear-only CSR bits
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/on_chip_debugger.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  sim/neorv32_tb.vhd
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu_csr.h
Labels: bug, HW

#832 [sw] remove unused variable RISCV_TOOLCHAIN
  sw/common/common.mk
  sw/ocd-firmware/makefile
Labels: SW

#834 :bug: fix GPTMR threshold = 0 configuration
  CHANGELOG.md
  rtl/core/neorv32_gptmr.vhd
  rtl/core/neorv32_package.vhd
  sw/example/processor_check/main.c
Labels: bug, HW

#835 Small correction in user guide
  docs/userguide/programming_an_external_spi_flash_via_bootloader.adoc
Labels: DOC
