Repository stnolting/neorv32, pull requests merged in 2025-04, with the labels that each got.

#1222 :bug: fix PWM prescaler
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_pwm.vhd
Labels: bug, HW

#1224 🐛 [linker] fix alignment of init/fini arrays
  sw/common/neorv32.ld
Labels: bug, SW

#1226 [sw/lib] add restart/reset functions
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_cpu.h
  sw/lib/include/neorv32_wdt.h
  sw/lib/source/neorv32_wdt.c
Labels: SW

#1228 [sw/lib/neoled] fix neoled "irq_mode" not a applied in "neorv32_neoled_setup" and [sw/lib/neoled] updated doxygen comments
  sw/lib/include/neorv32_neoled.h
  sw/lib/source/neorv32_neoled.c
Labels: bug, SW

#1230 Add support for setting PWM polarity
  CHANGELOG.md
  docs/datasheet/soc_pwm.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_pwm.vhd
  sw/lib/include/neorv32_pwm.h
  sw/lib/source/neorv32_pwm.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#1231 [sw] cleanup main software makefile, add git tag, add verbosity configuration
  docs/datasheet/software.adoc
  sw/common/common.mk
  sw/example/eclipse/.gitignore
  sw/example/eclipse/.settings/language.settings.xml
  sw/example/eclipse/.settings/org.eclipse.cdt.core.prefs
  sw/example/eclipse/.settings/org.eclipse.core.resources.prefs
  sw/example/eclipse/.settings/org.eclipse.embedcdt.debug.gdbjtag.openocd.core.prefs
  sw/example/eclipse/.settings/org.eclipse.embedcdt.managedbuild.cross.core.prefs
  sw/example/eclipse/.settings/org.eclipse.embedcdt.managedbuild.cross.riscv.core.prefs
  sw/example/eclipse/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/openocd/interface.cfg
Labels: SW

#1215 Rework bootloader
  docs/datasheet/software_bootloader.adoc
  docs/userguide/content.adoc
  docs/userguide/customizing_the_bootloader.adoc
  docs/userguide/programming_an_external_spi_flash_via_bootloader.adoc
  docs/userguide/using_the_neorv32_bootloader.adoc
  rtl/core/neorv32_bootloader_image.vhd
  sw/bootloader/README.md
  sw/bootloader/bootloader.c
  sw/bootloader/config.h
  sw/bootloader/hal/include/spi_flash.h
  sw/bootloader/hal/include/twi_flash.h
  sw/bootloader/hal/include/uart.h
  sw/bootloader/hal/source/spi_flash.c
  sw/bootloader/hal/source/twi_flash.c
  sw/bootloader/hal/source/uart.c
  sw/bootloader/main.c
  sw/bootloader/makefile
Labels: SW, coding-style, cleanup

#1236 [rtl/pmp] fix multiple signal assignment
  CHANGELOG.md
  docs/datasheet/soc_sdi.adoc
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_package.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
Labels: bug, HW

#1237 [rtl/core/twi] delay sda low
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_twi.vhd
Labels: HW

#1241 🐛 [bootloader] fix privilege at application start
  CHANGELOG.md
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  sw/bootloader/main.c
Labels: bug, SW

#1244 Optimize round-robin bus switch: remove idle cycles
  CHANGELOG.md
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_package.vhd
  sw/example/demo_dual_core_primes/Makefile
  sw/example/demo_dual_core_primes/main.c
Labels: HW, optimization

#1245 Add bus lock feature
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_clint.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_frontend.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_package.vhd
Labels: enhancement, HW, experimental

#1248 Optimize cache system
  CHANGELOG.md
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: HW, optimization

#1249 Rework newlib system calls
  CHANGELOG.md
  docs/datasheet/software.adoc
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  sw/example/demo_newlib/main.c
  sw/example/demo_newlib/makefile
  sw/example/eclipse/main.c
  sw/example/eclipse/makefile
  sw/lib/source/neorv32_newlib.c
Labels: SW, cleanup
