Repository stnolting/neorv32, pull requests merged in 2025-02, with the labels that each got.

#1174 Minor rtl optimizations and cleanups
  CHANGELOG.md
  docs/datasheet/soc_dma.adoc
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_xbus.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  rtl/system_integration/xbus2ahblite_bridge.vhd
  rtl/system_integration/xbus2axi4lite_bridge.vhd
  sim/neorv32_tb.vhd
  sim/xbus_gateway.vhd
  sim/xbus_memory.vhd
  sw/bootloader/bootloader.c
  sw/common/crt0.S
  sw/example/demo_dma/main.c
  sw/example/eclipse/.cproject
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_dma.h
  sw/lib/source/neorv32_dma.c
  sw/ocd-firmware/park_loop.S
  sw/svd/neorv32.svd
Labels: HW, optimization, cleanup

#1175 ⚠️ remove execute in-place (XIP) module
  CHANGELOG.md
  README.md
  docs/datasheet/on_chip_debugger.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/soc_xip.adoc
  docs/datasheet/software.adoc
  docs/datasheet/software_bootloader.adoc
  docs/figures/address_space.png
  docs/figures/neorv32_bus.png
  docs/figures/neorv32_processor.png
  docs/figures/ram_layout.png
  docs/userguide/customizing_the_bootloader.adoc
  docs/userguide/executable_upload.adoc
  docs/userguide/simulating_the_processor.adoc
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_xip.vhd
  rtl/file_list_soc.f
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sw/bootloader/bootloader.c
  sw/bootloader/makefile
  sw/example/demo_xip/main.c
  sw/example/demo_xip/makefile
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/include/neorv32_xip.h
  sw/lib/source/neorv32_aux.c
  sw/lib/source/neorv32_xip.c
  sw/svd/neorv32.svd
Labels: HW, cleanup

#1177 [cfs] Add missing CFS clock gen enable signal.
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: bug, HW

#1176 ✨ add memory coherency logic
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/on_chip_debugger.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/rationale.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_dcache.adoc
  docs/datasheet/soc_icache.adoc
  docs/datasheet/soc_wdt.adoc
  docs/datasheet/soc_xbus.adoc
  docs/datasheet/software.adoc
  docs/datasheet/software_bootloader.adoc
  docs/datasheet/software_rte.adoc
  docs/figures/bus_interface.png
  docs/sources/bus_interface.json
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_gpio.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_wdt.vhd
  rtl/core/neorv32_xbus.vhd
  rtl/file_list_soc.f
  sw/example/demo_wdt/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_wdt.h
  sw/lib/source/neorv32_wdt.c
  sw/svd/neorv32.svd
Labels: enhancement, HW, experimental

#1178 Doc ds fixes
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/cpu_dual_core.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_neoled.adoc
  docs/datasheet/soc_slink.adoc
  docs/datasheet/soc_xbus.adoc
Labels: DOC

#1166 [docs] SPI: minor fixes
  docs/datasheet/soc_gptmr.adoc
  docs/datasheet/soc_neoled.adoc
  docs/datasheet/soc_onewire.adoc
  docs/datasheet/soc_pwm.adoc
  docs/datasheet/soc_spi.adoc
  docs/datasheet/soc_twi.adoc
  docs/datasheet/soc_uart.adoc
Labels: DOC

#1180 :warning: rename UART RTS/CTS signals
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_uart.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_uart.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
Labels: HW

#1181 ✨ add support for Zalrsc ISA extension
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_xbus.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sw/example/demo_dual_core/main.c
  sw/example/demo_dual_core/spinlock.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu.h
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_aux.c
  sw/lib/source/neorv32_smp.c
Labels: enhancement, risc-v compliance, HW

#1182 Minor rtl optimizations and cleanups
  CHANGELOG.md
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_icc.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
Labels: HW, optimization

#1183 Source-out CPU front-end
  CHANGELOG.md
  docs/datasheet/overview.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_frontend.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_package.vhd
  rtl/file_list_cpu.f
  rtl/file_list_soc.f
  sw/example/processor_check/main.c
Labels: HW, cleanup

#1186 ⚠️ Software libraries cleanup
  docs/datasheet/software.adoc
  sw/example/demo_blink_led/main.c
  sw/example/demo_neopixel/main.c
  sw/example/demo_newlib/main.c
  sw/example/demo_pwm/main.c
  sw/example/demo_trng/main.c
  sw/example/demo_wdt/main.c
  sw/example/eclipse/main.c
  sw/example/eclipse/makefile
  sw/example/game_of_life/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_aux.h
  sw/lib/include/neorv32_cfs.h
  sw/lib/include/neorv32_clint.h
  sw/lib/include/neorv32_cpu.h
  sw/lib/include/neorv32_cpu_cfu.h
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/include/neorv32_crc.h
  sw/lib/include/neorv32_dma.h
  sw/lib/include/neorv32_gpio.h
  sw/lib/include/neorv32_gptmr.h
  sw/lib/include/neorv32_intrinsics.h
  sw/lib/include/neorv32_neoled.h
  sw/lib/include/neorv32_onewire.h
  sw/lib/include/neorv32_pwm.h
  sw/lib/include/neorv32_rte.h
  sw/lib/include/neorv32_sdi.h
  sw/lib/include/neorv32_slink.h
  sw/lib/include/neorv32_smp.h
  sw/lib/include/neorv32_spi.h
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/include/neorv32_trng.h
  sw/lib/include/neorv32_twd.h
  sw/lib/include/neorv32_twi.h
  sw/lib/include/neorv32_uart.h
  sw/lib/include/neorv32_wdt.h
  sw/lib/source/neorv32_aux.c
  sw/lib/source/neorv32_cpu.c
  sw/lib/source/neorv32_newlib.c
Labels: SW, coding-style, cleanup

#1189 Fix Bootloader Makefile UART_BAUD
  sw/bootloader/makefile
Labels: bug, SW

#1190 🐛 fix bug in Zalrsc ISA extension
  CHANGELOG.md
  docs/datasheet/soc.adoc
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
Labels: bug, HW

#1191 [rtl] minor edits and cleanups
  CHANGELOG.md
  rtl/core/neorv32_cfs.vhd
  rtl/core/neorv32_clint.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_crypto.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_package.vhd
  sw/example/processor_check/main.c
Labels: HW, cleanup

#1192 [cpu] relocate CPU counters
  CHANGELOG.md
  docs/datasheet/overview.adoc
  rtl/core/neorv32_clint.vhd
  rtl/core/neorv32_clockgate.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_counters.vhd
  rtl/core/neorv32_debug_auth.vhd
  rtl/core/neorv32_package.vhd
  rtl/file_list_cpu.f
  rtl/file_list_soc.f
  sw/lib/source/neorv32_cpu.c
Labels: HW, coding-style, cleanup
