Repository stnolting/neorv32, pull requests merged in 2025-01, with the labels that each got.

#1141 ⚠️✨ replace Zalrsc ISA extension by Zaamo ISA extension
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_dcache.adoc
  docs/datasheet/soc_icache.adoc
  docs/datasheet/soc_xbus.adoc
  docs/datasheet/software.adoc
  docs/figures/bus_interface_atomic.png
  docs/figures/neorv32_bus.png
  docs/figures/neorv32_processor.png
  docs/sources/bus_interface_atomic.json
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sw/example/atomic_test/main.c
  sw/example/atomic_test/makefile
  sw/example/demo_dual_core/main.c
  sw/example/demo_dual_core/run_check.sh
  sw/example/demo_dual_core/spinlock.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_cpu_amo.h
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_aux.c
  sw/lib/source/neorv32_cpu_amo.c
Labels: risc-v compliance, HW

#1142 ✨ [dual-core] add inter-core communication
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/cpu_dual_core.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/software.adoc
  docs/figures/smp_system.png
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_icc.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/file_list_cpu.f
  rtl/file_list_soc.f
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sw/common/crt0.S
  sw/example/demo_dual_core/main.c
  sw/example/demo_dual_core/run_check.sh
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/include/neorv32_legacy.h
  sw/lib/include/neorv32_rte.h
  sw/lib/include/neorv32_smp.h
  sw/lib/source/neorv32_rte.c
  sw/lib/source/neorv32_smp.c
Labels: enhancement, HW, SW

#1144 Minor rtl edits and cleanups
  CHANGELOG.md
  docs/datasheet/overview.adoc
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_core_complex.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_icc.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/file_list_soc.f
  sim/neorv32_tb.vhd
  sw/common/crt0.S
  sw/example/demo_dual_core/main.c
  sw/example/processor_check/main.c
  sw/lib/source/neorv32_smp.c
Labels: HW, cleanup

#1145 fix CSR read operations (side effects)
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: risc-v compliance, HW

#1108 [sw/bootloader] add TWI boot option
  README.md
  docs/datasheet/software_bootloader.adoc
  docs/userguide/customizing_the_bootloader.adoc
  docs/userguide/executable_upload.adoc
  sw/bootloader/bootloader.c
  sw/bootloader/makefile
Labels: enhancement, SW

#1146 SMP dual-core cleanups
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/cpu_dual_core.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/software.adoc
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_core_complex.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_icc.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/file_list_soc.f
  sw/common/crt0.S
  sw/example/demo_dual_core/main.c
  sw/example/demo_dual_core/spinlock.c
  sw/example/demo_dual_core/spinlock.h
  sw/example/demo_dual_core_icc/Makefile
  sw/example/demo_dual_core_icc/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/include/neorv32_smp.h
  sw/lib/source/neorv32_smp.c
Labels: HW, optimization, cleanup

#1149 [control] separate fence and fence.i instructions
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_dcache.adoc
  docs/datasheet/soc_icache.adoc
  docs/datasheet/soc_xbus.adoc
  docs/datasheet/soc_xip.adoc
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: enhancement, HW

#1150 ⚠️ [rte] use a single, global trap handler table
  CHANGELOG.md
  docs/datasheet/cpu_dual_core.adoc
  docs/datasheet/software_rte.adoc
  rtl/core/neorv32_package.vhd
  sw/example/demo_dual_core_rte/Makefile
  sw/example/demo_dual_core_rte/main.c
  sw/example/demo_dual_core_rte/spinlock.c
  sw/example/demo_dual_core_rte/spinlock.h
  sw/lib/include/neorv32_rte.h
  sw/lib/source/neorv32_rte.c
Labels: SW, cleanup

#1151 Minor rtl edits and cleanup; :bug: fix multiple drivers bug
  CHANGELOG.md
  docs/datasheet/cpu_csr.adoc
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/bootloader/bootloader.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_aux.h
  sw/lib/source/neorv32_aux.c
Labels: bug, HW, cleanup

#1153 [sw/bootloader] aligned trap handler
  sw/bootloader/bootloader.c
Labels: SW

#1152 [top] add WDT and OCD reset outputs
  CHANGELOG.md
  docs/datasheet/on_chip_debugger.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_wdt.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sys.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
Labels: enhancement, HW

#1159 ✨ add GPIO interrupt(s)
  CHANGELOG.md
  README.md
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_gpio.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/soc_xirq.adoc
  docs/datasheet/software.adoc
  docs/figures/neorv32_processor.png
  docs/userguide/adding_custom_hw_modules.adoc
  docs/userguide/application_specific_configuration.adoc
  rtl/core/neorv32_application_image.vhd
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_gpio.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_xirq.vhd
  rtl/file_list_soc.f
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sw/example/demo_gpio/Makefile
  sw/example/demo_gpio/main.c
  sw/example/demo_xirq/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_gpio.h
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/include/neorv32_xirq.h
  sw/lib/source/neorv32_aux.c
  sw/lib/source/neorv32_gpio.c
  sw/lib/source/neorv32_xirq.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#1160 [ci] update GHDL setup
  .github/workflows/Processor.yml
Labels: CI

#1156 Update neorv32_ProcessorTop_MinimalBoot.vhd
  rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
Labels: HW

#1161 🐛 [twd] fix some design flaws
  CHANGELOG.md
  docs/datasheet/soc_twd.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_twd.vhd
  sw/example/processor_check/main.c
Labels: bug, HW

#1163 atomic memory access updates and improvements
  CHANGELOG.md
  docs/datasheet/soc_xbus.adoc
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_xbus.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/xbus2axi4lite_bridge.vhd
Labels: enhancement, HW, experimental

#1167 [rtl] reset SDA and SCL of TWI and TWD to '1'
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_twd.vhd
  rtl/core/neorv32_twi.vhd
Labels: HW

#1171 🐛 fix BOOTROM addressing
  CHANGELOG.md
  rtl/core/neorv32_boot_rom.vhd
  rtl/core/neorv32_package.vhd
  sw/lib/include/neorv32.h
Labels: bug, HW

#1172 🐛 Fix crt0's main entry address being overridden by constructors
  CHANGELOG.md
  rtl/core/neorv32_package.vhd
  sw/common/crt0.S
  sw/example/processor_check/main.c
Labels: bug, SW
