Repository stnolting/neorv32, pull requests merged in 2025-07, with the labels that each got.

#1304 ✨ add configurable number of break-/watchpoints
  CHANGELOG.md
  docs/datasheet/on_chip_debugger.adoc
  docs/datasheet/soc.adoc
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_libero_ip.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
Labels: enhancement, HW

#1307 minor rtl edits and cleanups
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_hwtrig.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_xbus.vhd
Labels: HW, coding-style, cleanup

#1313 ✨ add new module: execution trace buffer (TRACER)
  CHANGELOG.md
  README.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/soc_tracer.adoc
  docs/datasheet/software.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_tracer.vhd
  rtl/file_list_soc.f
  rtl/system_integration/neorv32_libero_ip.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sw/example/demo_tracer/Makefile
  sw/example/demo_tracer/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/include/neorv32_tracer.h
  sw/lib/source/neorv32_aux.c
  sw/lib/source/neorv32_tracer.c
  sw/svd/neorv32.svd
Labels: enhancement, HW

#1314 Cleanup UART simulation logging
  CHANGELOG.md
  docs/datasheet/soc_uart.adoc
  docs/userguide/simulating_the_processor.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_uart.vhd
  sim/ghdl.sh
  sim/neorv32_tb.vhd
  sim/sim_uart_rx.vhd
  sw/example/demo_semihosting/makefile
  sw/example/hello_world/makefile
  sw/example/processor_check/makefile
Labels: HW, CI

#1316 Replace trace with trace_s in the top
  rtl/core/neorv32_top.vhd
Labels: HW

#1317 Add GDB tracer support
  docs/datasheet/soc_tracer.adoc
  sw/example/demo_tracer/main.c
  sw/example/demo_tracer/neorv32_tracer.gdb
Labels: enhancement, SW

#1324 Make cache/AXI bursts optional
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_dcache.adoc
  docs/datasheet/soc_icache.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/soc_xbus.adoc
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  rtl/system_integration/xbus2axi4_bridge.vhd
  sim/neorv32_tb.vhd
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_aux.c
  sw/svd/neorv32.svd
Labels: enhancement, HW
