Repository stnolting/neorv32, pull requests merged in 2025-05, with the labels that each got.

#1252 ⚠️ Rework processor-internal bus protocol
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cfs.vhd
  rtl/core/neorv32_cpu_frontend.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_xbus.vhd
  sim/xbus_gateway.vhd
Labels: HW, optimization

#1253 Add full-scale AXI4 bridge
  CHANGELOG.md
  README.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_xbus.adoc
  docs/legal.adoc
  docs/userguide/adding_custom_hw_modules.adoc
  docs/userguide/packaging_vivado.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_xbus.vhd
  rtl/system_integration/README.md
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  rtl/system_integration/xbus2ahblite_bridge.vhd
  rtl/system_integration/xbus2axi4_bridge.vhd
  sim/xbus_gateway.vhd
Labels: bug, enhancement, HW

#1255 [docs] fix dead link to setups
  rtl/processor_templates/README.md
Labels: DOC

#1256 ⚠️ Remove external bus interface cache (xbus-cache)
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_pwm.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/soc_xbus.adoc
  docs/figures/neorv32_bus.png
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_aux.c
  sw/svd/neorv32.svd
Labels: HW, cleanup

#1257 :warning: Rework cache configuration options
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_dual_core.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_dcache.adoc
  docs/datasheet/soc_icache.adoc
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cpu_frontend.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sw/lib/source/neorv32_aux.c
Labels: HW, cleanup

#1259 Rework caches; use "write-through" strategy
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_dcache.adoc
  docs/datasheet/soc_icache.adoc
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/example/processor_check/main.c
Labels: HW

#1260 Rework locking of processor-internal bus
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_xbus.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/xbus2axi4_bridge.vhd
  sim/neorv32_tb.vhd
Labels: enhancement, HW

#1262 minor edits and optimizations
  CHANGELOG.md
  docs/datasheet/on_chip_debugger.adoc
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_debug_dm.vhd
  rtl/core/neorv32_package.vhd
  sw/bootloader/main.c
  sw/ocd-firmware/README.md
  sw/ocd-firmware/debug_rom.ld
  sw/ocd-firmware/park_loop.S
Labels: HW, SW, optimization

#1263 ✨ add cache burst transfers
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_dual_core.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_dcache.adoc
  docs/datasheet/soc_icache.adoc
  docs/datasheet/soc_xbus.adoc
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_xbus.vhd
  rtl/system_integration/neorv32_vivado_ip.vhd
  rtl/system_integration/xbus2axi4_bridge.vhd
  sim/neorv32_tb.vhd
Labels: enhancement, HW, experimental

#1265 [bus] add explicit burst signal to internal processor bus
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_frontend.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_xbus.vhd
Labels: HW, cleanup

#1266 🐛 Fix missing burst signal in bus register stage
  CHANGELOG.md
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, HW

#1268 ⚠️ [inter-processor communication] remove hardware spinlocks and inter-core communication links
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/cpu_dual_core.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_hwspinlock.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/figures/neorv32_processor.png
  docs/figures/smp_system.png
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_icc.vhd
  rtl/core/neorv32_hwspinlock.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/file_list_cpu.f
  rtl/file_list_soc.f
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sw/bootloader/main.c
  sw/common/crt0.S
  sw/example/demo_dual_core/spinlock.c
  sw/example/demo_dual_core_hwspinlock/Makefile
  sw/example/demo_dual_core_hwspinlock/main.c
  sw/example/demo_dual_core_icc/Makefile
  sw/example/demo_dual_core_icc/main.c
  sw/example/demo_dual_core_primes/Makefile
  sw/example/demo_dual_core_primes/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_hwspinlock.h
  sw/lib/include/neorv32_smp.h
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_aux.c
  sw/lib/source/neorv32_hwspinlock.c
  sw/lib/source/neorv32_smp.c
Labels: HW, cleanup

#1270 :bug: fix CPU bus issues
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/soc_xbus.adoc
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu_lsu.vhd
  rtl/core/neorv32_package.vhd
  sim/xbus_memory.vhd
Labels: bug, HW

#1272 :bug: fix byte-enable bus signal for instruction fetch accesses
  CHANGELOG.md
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cpu_frontend.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, HW

#1275 ⚠️ remove CRC module
  CHANGELOG.md
  README.md
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_crc.adoc
  docs/datasheet/soc_dma.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/datasheet/software.adoc
  docs/figures/neorv32_processor.png
  docs/userguide/simulating_the_processor.adoc
  rtl/core/neorv32_crc.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/file_list_soc.f
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sw/example/demo_crc/main.c
  sw/example/demo_crc/makefile
  sw/example/processor_check/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_crc.h
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_aux.c
  sw/lib/source/neorv32_crc.c
  sw/svd/neorv32.svd
Labels: HW, cleanup

#1277 Rework IMEM & DMEM RAM style
  CHANGELOG.md
  rtl/core/neorv32_dmem.vhd
  rtl/core/neorv32_imem.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, optimization

#1278 [cpu] rework instruction trap logic
  CHANGELOG.md
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, HW

#1279 🧪 rework DMA controller
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_dma.adoc
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sw/example/demo_dma/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_dma.h
  sw/lib/source/neorv32_dma.c
  sw/svd/neorv32.svd
Labels: bug, HW, SW, experimental

#1280 ⚠️ Rename IMEM/DMEM configuration generics
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_dmem.adoc
  docs/datasheet/soc_imem.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/userguide/application_specific_configuration.adoc
  docs/userguide/general_hw_setup.adoc
  docs/userguide/general_sw_framework_setup.adoc
  docs/userguide/installing_an_executable.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd
  rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
  rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  rtl/test_setups/README.md
  rtl/test_setups/neorv32_test_setup_approm.vhd
  rtl/test_setups/neorv32_test_setup_bootloader.vhd
  rtl/test_setups/neorv32_test_setup_on_chip_debugger.vhd
  sim/neorv32_tb.vhd
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_aux.c
  sw/svd/neorv32.svd
Labels: HW, cleanup
