Repository stnolting/neorv32, pull requests merged in 2025-08, with the labels that each got.

#1331 minor rtl edits and cleanups
  CHANGELOG.md
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_cpu_cp_crypto.vhd
  rtl/core/neorv32_cpu_cp_muldiv.vhd
  rtl/core/neorv32_cpu_pmp.vhd
  rtl/core/neorv32_package.vhd
Labels: HW, cleanup

#1333 minor fixes and optimizations
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_cpu_hwtrig.vhd
  rtl/core/neorv32_package.vhd
  sw/example/processor_check/main.c
  sw/lib/source/neorv32_rte.c
Labels: HW, SW, optimization

#1339 Rework bus access error logic
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_dcache.adoc
  docs/datasheet/soc_icache.adoc
  docs/datasheet/soc_xbus.adoc
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_xbus.vhd
  rtl/system_integration/neorv32_libero_ip.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sim/xbus_gateway.vhd
  sw/example/processor_check/main.c
Labels: HW, optimization

#1342 ⚠️ [SYSINFO] rework layout of "MISC" information register
  CHANGELOG.md
  docs/datasheet/soc_sysinfo.adoc
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  sw/bootloader/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_aux.c
  sw/svd/neorv32.svd
Labels: HW

#1344 [rtl] replace individual IMEM & DMEM modules by a generic memory component
  CHANGELOG.md
  docs/datasheet/overview.adoc
  docs/datasheet/soc_dmem.adoc
  docs/datasheet/soc_imem.adoc
  rtl/core/neorv32_dmem.vhd
  rtl/core/neorv32_mem.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/file_list_soc.f
Labels: HW, coding-style, cleanup

#1345 rtl code cleanups and optimizations
  CHANGELOG.md
  rtl/core/neorv32_cpu_frontend.vhd
  rtl/core/neorv32_cpu_regfile.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_fifo.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_onewire.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sdi.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_tracer.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_twd.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_uart.vhd
  rtl/file_list_cpu.f
  sim/neorv32_tb.vhd
Labels: HW, optimization

#1347 [rtl] derive all memories from generic RAM primitives
  CHANGELOG.md
  docs/datasheet/overview.adoc
  docs/datasheet/soc_dmem.adoc
  docs/datasheet/soc_imem.adoc
  rtl/core/neorv32_boot_rom.vhd
  rtl/core/neorv32_cache.vhd
  rtl/core/neorv32_cpu_regfile.vhd
  rtl/core/neorv32_dmem.vhd
  rtl/core/neorv32_imem.vhd
  rtl/core/neorv32_mem.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_prim.vhd
  rtl/core/neorv32_top.vhd
  rtl/file_list_cpu.f
  rtl/file_list_soc.f
  sim/neorv32_tb.vhd
  sw/example/processor_check/main.c
Labels: HW, coding-style, cleanup

#1349 [rtl] add all-new FIFO primitive
  CHANGELOG.md
  docs/datasheet/overview.adoc
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_fifo.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_onewire.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_prim.vhd
  rtl/core/neorv32_sdi.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_tracer.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_twd.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_uart.vhd
  rtl/file_list_soc.f
  sim/neorv32_tb.vhd
  sw/example/processor_check/main.c
Labels: HW, optimization, cleanup

#1350 [demo_semihosting] use 4-byte instead of 16-byte alignment
  sw/lib/include/neorv32_semihosting.h
Labels: bug, SW

#1354 ⚠️ simplify UART and SDI modules
  CHANGELOG.md
  docs/datasheet/soc_sdi.adoc
  docs/datasheet/soc_uart.adoc
  rtl/core/neorv32_bootloader_image.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_onewire.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_prim.vhd
  rtl/core/neorv32_sdi.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_tracer.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_twd.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_uart.vhd
  sim/neorv32_tb.vhd
  sw/example/demo_sdi/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_sdi.h
  sw/lib/include/neorv32_spi.h
  sw/lib/include/neorv32_uart.h
  sw/lib/source/neorv32_sdi.c
  sw/lib/source/neorv32_spi.c
  sw/lib/source/neorv32_uart.c
  sw/svd/neorv32.svd
Labels: HW, optimization, cleanup
