Repository stnolting/neorv32, pull requests merged in 2025-03, with the labels that each got.

#1193 minor rtl edits
  CHANGELOG.md
  rtl/core/neorv32_bus.vhd
  rtl/core/neorv32_cpu_alu.vhd
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_cpu_cp_shifter.vhd
  rtl/core/neorv32_cpu_frontend.vhd
  rtl/core/neorv32_dmem.vhd
  rtl/core/neorv32_imem.vhd
  rtl/core/neorv32_neoled.vhd
  rtl/core/neorv32_onewire.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sdi.vhd
  rtl/core/neorv32_slink.vhd
  rtl/core/neorv32_spi.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_trng.vhd
  rtl/core/neorv32_twd.vhd
  rtl/core/neorv32_twi.vhd
  rtl/core/neorv32_uart.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
Labels: HW, coding-style

#1194 ⚠️ rework DMA and GPTMR
  CHANGELOG.md
  docs/datasheet/soc_dma.adoc
  docs/datasheet/soc_gptmr.adoc
  rtl/core/neorv32_crc.vhd
  rtl/core/neorv32_dma.vhd
  rtl/core/neorv32_gptmr.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  sw/example/demo_crc/main.c
  sw/example/demo_dma/main.c
  sw/example/demo_gptmr/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_cpu.h
  sw/lib/include/neorv32_dma.h
  sw/lib/include/neorv32_gptmr.h
  sw/lib/source/neorv32_dma.c
  sw/lib/source/neorv32_gptmr.c
  sw/svd/neorv32.svd
Labels: HW, cleanup

#1196 rtl: processor_templates: enable Zicntr ISA extension on minimal templates
  rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd
  rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd
Labels: risc-v compliance, HW

#1197 Fix: quote readlink to fix windows make check
  sw/common/common.mk
Labels: bug, SW

#1201 fix: increment location counter with heap size
  sw/common/neorv32.ld
Labels: bug, SW

#1204 Add NUMA LiteX configuration
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/system_integration/neorv32_litex_core_complex.vhd
Labels: enhancement, HW

#1206 :bug: Fix `Zbb` shift instructions
  CHANGELOG.md
  rtl/core/neorv32_cpu_cp_bitmanip.vhd
  rtl/core/neorv32_package.vhd
Labels: bug, HW

#1207 :warning: rename SPI & TWI transfer functions
  sw/bootloader/bootloader.c
  sw/example/demo_spi/main.c
  sw/example/demo_twi/main.c
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_spi.h
  sw/lib/include/neorv32_twi.h
  sw/lib/source/neorv32_spi.c
  sw/lib/source/neorv32_twi.c
Labels: SW

#1208 [docs] inline Wavedrom scripts
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_cfu.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc_neoled.adoc
  docs/datasheet/soc_onewire.adoc
  docs/datasheet/soc_slink.adoc
  docs/datasheet/soc_twd.adoc
  docs/datasheet/soc_xbus.adoc
  docs/figures/.gitignore
  docs/figures/bus_interface.png
  docs/figures/cfu_r3type_instruction.png
  docs/figures/cfu_r4type_instruction.png
  docs/figures/neopixel_timing.png
  docs/figures/onewire_data.png
  docs/figures/onewire_reset.png
  docs/figures/stream_link_interface.png
  docs/figures/xbus_read.png
  docs/figures/xbus_write.png
  docs/legal.adoc
  docs/sources/bus_interface.json
  docs/sources/cfu_r3type_instruction.json
  docs/sources/cfu_r4type_instruction.json
  docs/sources/neopixel_timing.json
  docs/sources/onewire_data.json
  docs/sources/onewire_reset.json
  docs/sources/stream_link_interface.json
  docs/sources/twd_sequences.json
  docs/sources/xbus_read.json
  docs/sources/xbus_write.json
Labels: DOC, experimental

#1209 docs: datasheet: cpu: fix name for the "A" ISA extension
  docs/datasheet/cpu.adoc
Labels: DOC

#1212 build: rebuild exe when header files change
  sw/common/common.mk
  sw/example/demo_onewire/makefile
  sw/example/demo_pwm/makefile
  sw/example/demo_slink/makefile
  sw/example/demo_spi/makefile
  sw/example/demo_trng/makefile
  sw/example/demo_twi/makefile
  sw/example/demo_wdt/makefile
  sw/example/dhrystone/makefile
  sw/example/float_corner_test/makefile
Labels: SW

#1214 ⚠️ Remove CPU clock gating option
  CHANGELOG.md
  docs/datasheet/cpu.adoc
  docs/datasheet/cpu_csr.adoc
  docs/datasheet/cpu_dual_core.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  rtl/core/neorv32_clockgate.vhd
  rtl/core/neorv32_cpu.vhd
  rtl/core/neorv32_cpu_control.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/file_list_cpu.f
  rtl/file_list_soc.f
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sw/lib/include/neorv32_cpu_csr.h
  sw/lib/source/neorv32_aux.c
Labels: HW

#1210 [rtl/sw] Add twd dummy byte, add twd bootloader and smaller fixes
  CHANGELOG.md
  docs/datasheet/soc.adoc
  docs/datasheet/soc_twd.adoc
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_top.vhd
  rtl/core/neorv32_twd.vhd
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sw/example/demo_twd/main.c
  sw/example/demo_twd/makefile
  sw/example/processor_check/main.c
  sw/lib/include/neorv32_twd.h
  sw/lib/source/neorv32_twd.c
Labels: enhancement, HW, SW

#1220 ✨ Add 32 hardware spinlocks
  CHANGELOG.md
  README.md
  docs/datasheet/cpu.adoc
  docs/datasheet/overview.adoc
  docs/datasheet/soc.adoc
  docs/datasheet/soc_hwspinlock.adoc
  docs/datasheet/soc_sysinfo.adoc
  docs/figures/neorv32_processor.png
  rtl/core/neorv32_hwspinlock.vhd
  rtl/core/neorv32_package.vhd
  rtl/core/neorv32_sysinfo.vhd
  rtl/core/neorv32_top.vhd
  rtl/file_list_soc.f
  rtl/system_integration/neorv32_vivado_ip.tcl
  rtl/system_integration/neorv32_vivado_ip.vhd
  sim/neorv32_tb.vhd
  sw/example/demo_dual_core_hwspinlock/Makefile
  sw/example/demo_dual_core_hwspinlock/main.c
  sw/lib/include/neorv32.h
  sw/lib/include/neorv32_hwspinlock.h
  sw/lib/include/neorv32_sysinfo.h
  sw/lib/source/neorv32_aux.c
  sw/lib/source/neorv32_hwspinlock.c
  sw/svd/neorv32.svd
Labels: enhancement, HW, SW
